# Generated by Django 5.0.1 on 2026-04-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('cutting_master', 'Cutting Master'), ('dhage_katne_wala', 'Dhage Katne Wala'), ('embroidery', 'Embroidery'), ('tailoring', 'Tailoring'), ('other', 'Other')], max_length=50, unique=True),
        ),
    ]
