# Generated by Django 5.0.1 on 2026-04-23 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_skill_name'),
        ('inventory', '0009_batchstagemachineassignment_batchtype_batchtypestage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='RBAC role — determines permissions and sidebar visibility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='inventory.role', verbose_name='Role'),
        ),
    ]
