# Generated by Django 5.0.1 on 2026-05-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('karigar', 'Karigar'), ('helper', 'Helper'), ('normal', 'Normal')], default='karigar', max_length=20, verbose_name='User Type'),
        ),
    ]
