# Generated by Django 5.0.1 on 2026-05-17 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_extra_roles'),
        ('inventory', '0011_seed_listing_team_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Primary RBAC role — determines main permissions and sidebar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='inventory.role', verbose_name='Role'),
        ),
    ]
