# Generated by Django 5.0.1 on 2026-05-19 19:58
# Hand-edited to seed the new Skill row alongside the schema change.

from django.db import migrations, models


def seed_skill_rows(apps, schema_editor):
    """Stage transition workflows ke saare skill rows guarantee karo.

    Older migrations sirf SKILL_TYPE_CHOICES enum extend karti thi — Skill table
    khali rehti thi. Naya Layering workflow `cutting_master` aur `cutting_master_helper`
    dono rows pe depend karta hai (services + tests), isliye dono yahan idempotently seed.

    get_or_create idempotent — repeat migrate ya seed scripts kabhi double-create na karein.
    """
    Skill = apps.get_model('accounts', 'Skill')
    for name in ('cutting_master', 'cutting_master_helper'):
        Skill.objects.get_or_create(name=name)


def remove_seeded_skill_rows(apps, schema_editor):
    """Reverse migration — sirf is migration ne add ki rows hatao.

    cutting_master pehle se M2M se attach ho sakta hai (user ke skills mein) —
    isliye safety ke liye delete sirf cutting_master_helper ka, jo strictly is
    migration mein add hua. cutting_master ko untouched chhodte hain.
    """
    Skill = apps.get_model('accounts', 'Skill')
    Skill.objects.filter(name='cutting_master_helper').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('cutting_master', 'Cutting Master'), ('cutting_master_helper', 'Cutting Master Helper'), ('dhage_katne_wala', 'Dhage Katne Wala'), ('embroidery', 'Embroidery'), ('tailoring', 'Tailoring'), ('other', 'Other')], max_length=50, unique=True),
        ),
        migrations.RunPython(seed_skill_rows, remove_seeded_skill_rows),
    ]
