# Generated by Django 5.0.1 on 2026-06-02 08:57 — + data migration (RBAC cleanup).

from django.db import migrations, models


# Preserve current access by writing an EXPLICIT Role onto every role=None user,
# using the OLD user_type semantics, BEFORE renaming the user_type values. After
# this, access no longer depends on the user_type→role fallback.
_OLD_TYPE_TO_ROLE = {
    'admin': 'super_admin', 'manager': 'manager',
    'karigar': 'karigar', 'helper': 'karigar', 'normal': None,
}
# Old user_type display value → new spec value.
_OLD_TYPE_TO_NEW = {
    'admin': 'admin', 'manager': 'admin',
    'karigar': 'worker', 'helper': 'worker', 'normal': 'normal',
}


def forwards(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Role = apps.get_model('inventory', 'Role')
    roles = {r.code: r for r in Role.objects.all()}
    for u in User.objects.all():
        old = u.user_type
        # 1. Assign an explicit Role where missing (preserve current access).
        if u.role_id is None:
            code = 'super_admin' if u.is_superuser else _OLD_TYPE_TO_ROLE.get(old)
            if code and roles.get(code):
                u.role = roles[code]
        # 2. Rename user_type to the new spec value (display only).
        u.user_type = 'superadmin' if u.is_superuser else _OLD_TYPE_TO_NEW.get(old, 'normal')
        u.save(update_fields=['role', 'user_type'])


def backwards(apps, schema_editor):
    # Lossy (admin+manager both mapped to 'admin'); restore the worker label only.
    # Roles are intentionally NOT stripped on reverse (keep explicit grants).
    User = apps.get_model('accounts', 'User')
    User.objects.filter(user_type='worker').update(user_type='karigar')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_cutting_master_helper_skill'),
        # Role lives in inventory; ensure it exists before we assign it.
        ('inventory', '0018_tighten_products_seed_access_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('worker', 'Worker'), ('supplier', 'Supplier'), ('normal', 'Normal')], default='worker', max_length=20, verbose_name='User Type'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
