# Generated by Django 5.0.1 on 2026-06-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usertype_model_skill_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['label']},
        ),
    ]
