# Generated by Django 5.0.1 on 2026-06-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_skill_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0019_rename_karigar_role_to_worker'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'role'], name='accounts_us_is_acti_5e865e_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('salary__gte', 0)), name='accounts_user_salary_nonneg'),
        ),
    ]
