# Generated by Django 5.0.1 on 2026-06-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_accounts_us_is_acti_5e865e_idx_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='System roles (admin/manager/worker) cannot be deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='inventory_roles', to='auth.permission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='extra_roles',
            field=models.ManyToManyField(blank=True, help_text='Additional access grants. Stack on top of the primary role.', related_name='extra_users', to='accounts.role', verbose_name='Extra Roles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Primary RBAC role — determines main permissions and sidebar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role', verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='SidebarItemRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(help_text="Django URL name, e.g. 'raw_materials:roll-list'.", max_length=128, unique=True)),
                ('section', models.CharField(help_text='Display section header.', max_length=64)),
                ('label', models.CharField(help_text='Display label in the sidebar.', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, help_text='Roles allowed to see this menu item.', related_name='visible_sidebar_items', to='accounts.role')),
                ('allowed_skills', models.ManyToManyField(blank=True, help_text='Users with ANY of these skills also see this menu item.', related_name='visible_sidebar_items', to='accounts.skill')),
            ],
            options={
                'ordering': ['section', 'label'],
            },
        ),
    ]
