# Generated by Django 5.2.3 on 2025-06-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_authenticated',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
