# Generated by Django 5.2.3 on 2025-06-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_created_at_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('cutting_master', 'Cutting Master'), ('supplier', 'Supplier'), ('karigar', 'Karigar'), ('kapde_wala', 'Kapde Wala')], default='karigar', max_length=20),
        ),
    ]
