# Generated by Django 5.2.3 on 2025-06-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cutting_master', 'Cutting Master'), ('dhage_katne_wala', 'Dhage Katne Wala'), ('embroidery', 'Embroidery'), ('tailoring', 'Tailoring'), ('other', 'Other')], max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('supplier', 'Supplier'), ('karigar', 'Karigar'), ('kapde_wala', 'Kapde Wala')], default='karigar', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.skill'),
        ),
    ]
