# Generated by Django 5.0.1 on 2026-05-19 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0004_cuttingrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('piece_seq', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('missing', 'Missing')], default='pending', max_length=16)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('adda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcodes', to='production.adda')),
                ('last_scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['adda', 'piece_seq'],
                'indexes': [models.Index(fields=['adda', 'status'], name='tracking_ba_adda_id_6321d0_idx'), models.Index(fields=['status'], name='tracking_ba_status_2fd4f1_idx')],
                'unique_together': {('adda', 'piece_seq')},
            },
        ),
    ]
