# Generated by Django 5.0.1 on 2026-05-19 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_cuttingrecord'),
        ('raw_materials', '0005_clothroll_adda_clothroll_used_at_clothroll_used_by'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('stage_advanced', 'Stage Advanced'), ('status_changed', 'Status Changed'), ('roll_assigned', 'Roll Assigned'), ('completed', 'Completed')], max_length=32)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('adda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='production.adda')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='raw_materials.clothroll')),
                ('stage_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.workflowstage')),
                ('stage_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.workflowstage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['adda', '-created_at'], name='tracking_ad_adda_id_1eb23d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClothRollHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('location_moved', 'Location Moved'), ('weight_updated', 'Weight Updated'), ('archived', 'Archived')], max_length=32)),
                ('field_name', models.CharField(blank=True, max_length=64)),
                ('old_value', models.CharField(blank=True, max_length=200)),
                ('new_value', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='raw_materials.clothroll')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['roll', '-created_at'], name='tracking_cl_roll_id_3bbd6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('archived', 'Archived')], max_length=32)),
                ('field_name', models.CharField(blank=True, max_length=64)),
                ('old_value', models.CharField(blank=True, max_length=200)),
                ('new_value', models.CharField(blank=True, max_length=200)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='production.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='tracking_pr_product_775b39_idx')],
            },
        ),
    ]
