# Generated by Django 5.0.1 on 2026-05-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_addahistory_clothrollhistory_producthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='addahistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='batchbarcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clothrollhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
