# Generated by Django 5.0.1 on 2026-05-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_addahistory_updated_at_batchbarcode_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addahistory',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('stage_advanced', 'Stage Advanced'), ('stage_reopened', 'Stage Reopened'), ('status_changed', 'Status Changed'), ('roll_assigned', 'Roll Assigned'), ('completed', 'Completed')], max_length=32),
        ),
    ]
