# Generated by Django 5.0.1 on 2026-05-28 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_productsize_cuttingpatternverification_and_more'),
        ('raw_materials', '0008_phase6_draft_and_denormalized_leftover'),
        ('tracking', '0004_alter_addahistory_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchbarcode',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='raw_materials.clothcolor'),
        ),
        migrations.AddField(
            model_name='batchbarcode',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productpattern'),
        ),
        migrations.AddField(
            model_name='batchbarcode',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='raw_materials.clothroll'),
        ),
        migrations.AddField(
            model_name='batchbarcode',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productsize'),
        ),
    ]
