# Generated by Django 5.0.1 on 2026-05-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_productsize_cuttingpatternverification_and_more'),
        ('raw_materials', '0008_phase6_draft_and_denormalized_leftover'),
        ('tracking', '0005_batchbarcode_color_batchbarcode_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_seq', models.PositiveIntegerField()),
                ('end_seq', models.PositiveIntegerField()),
                ('total_pieces', models.PositiveIntegerField()),
                ('adda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcode_batches', to='production.adda')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='raw_materials.clothcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productsize')),
            ],
            options={
                'ordering': ['adda', 'start_seq'],
            },
        ),
        migrations.AddField(
            model_name='batchbarcode',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scanned_pieces', to='tracking.barcodebatch'),
        ),
        migrations.AddIndex(
            model_name='barcodebatch',
            index=models.Index(fields=['adda', 'start_seq'], name='tracking_ba_adda_id_e3be5e_idx'),
        ),
        migrations.AddIndex(
            model_name='barcodebatch',
            index=models.Index(fields=['adda', 'end_seq'], name='tracking_ba_adda_id_8683fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='barcodebatch',
            unique_together={('adda', 'color', 'size')},
        ),
    ]
