# Generated by Django 5.0.1 on 2026-05-28 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_cuttingbundleitem_source_breakup_and_more'),
        ('tracking', '0006_barcodebatch_batchbarcode_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodebatch',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='barcode_batches', to='production.cuttingbundle'),
        ),
    ]
