# Generated by Django 5.0.1 on 2026-05-29 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_labelprintqueue_addaproductsizecolorpiecebreakdown_and_more'),
        ('tracking', '0008_batchbarcode_size_color_status_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeExportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_code', models.CharField(max_length=24, unique=True)),
                ('export_method', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF Summary')], max_length=8)),
                ('total_labels', models.PositiveIntegerField()),
                ('adda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcode_exports', to='production.adda')),
                ('barcode_gen_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='production.barcodegenerationrecord')),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['adda', '-created_at'], name='tracking_ba_adda_id_34964e_idx'), models.Index(fields=['-created_at'], name='tracking_ba_created_e0f8e1_idx')],
            },
        ),
    ]
