# Generated by Django 5.0.1 on 2026-06-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_barcodeexportbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='addahistory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='addahistory',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('stage_advanced', 'Stage Advanced'), ('stage_reopened', 'Stage Reopened'), ('status_changed', 'Status Changed'), ('roll_assigned', 'Roll Assigned'), ('completed', 'Completed'), ('cost_frozen', 'Cost Frozen')], max_length=32),
        ),
    ]
