# Generated by Django 5.0.1 on 2026-06-01 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_addastagerecord_cost_frozen_at_and_more'),
        ('tracking', '0010_addahistory_metadata_alter_addahistory_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addahistory',
            name='stage_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.addastagerecord'),
        ),
        migrations.AlterField(
            model_name='addahistory',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('stage_advanced', 'Stage Advanced'), ('stage_reopened', 'Stage Reopened'), ('status_changed', 'Status Changed'), ('roll_assigned', 'Roll Assigned'), ('completed', 'Completed'), ('cost_frozen', 'Cost Frozen'), ('stage_started', 'Stage Started'), ('workers_assigned', 'Workers Assigned'), ('bundle_created', 'Bundle Created'), ('barcodes_generated', 'Barcodes Generated'), ('exported', 'Exported')], max_length=32),
        ),
    ]
