# Generated by Django 5.0.1 on 2026-06-06 09:49

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_alter_addastagerecord_adda_and_more'),
        ('raw_materials', '0010_alter_clothcolor_hex_code_and_more'),
        ('tracking', '0012_alter_addahistory_change_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batchbarcode',
            index=models.Index(fields=['batch', 'status'], name='tracking_ba_batch_i_5e8f64_idx'),
        ),
        migrations.AddIndex(
            model_name='batchbarcode',
            index=models.Index(fields=['-last_scanned_at'], name='tracking_ba_last_sc_e3b0f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='barcodebatch',
            constraint=models.CheckConstraint(check=models.Q(('end_seq__gte', models.F('start_seq'))), name='tracking_batch_seq_order'),
        ),
        migrations.AddConstraint(
            model_name='barcodebatch',
            constraint=models.CheckConstraint(check=models.Q(('total_pieces__gt', 0)), name='tracking_batch_pieces_positive'),
        ),
        migrations.AddConstraint(
            model_name='barcodebatch',
            constraint=models.CheckConstraint(check=models.Q(('total_pieces', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('end_seq'), '-', models.F('start_seq')), '+', models.Value(1)))), name='tracking_batch_pieces_consistent'),
        ),
    ]
