# Generated by Django 5.0.1 on 2026-06-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_batchbarcode_tracking_ba_batch_i_5e8f64_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addahistory',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('stage_advanced', 'Stage Advanced'), ('stage_reopened', 'Stage Reopened'), ('status_changed', 'Status Changed'), ('roll_assigned', 'Roll Assigned'), ('roll_removed', 'Roll Removed'), ('completed', 'Completed'), ('cost_frozen', 'Cost Frozen'), ('stage_started', 'Stage Started'), ('workers_assigned', 'Workers Assigned'), ('bundle_created', 'Bundle Created'), ('barcodes_generated', 'Barcodes Generated'), ('exported', 'Exported'), ('settlement_finalized', 'Settlement Finalized'), ('settlement_reversed', 'Settlement Reversed'), ('settlement_superseded', 'Settlement Superseded')], max_length=32),
        ),
    ]
