# Generated by Django 5.0.1 on 2026-07-06 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0049_addastagerecord_production__complet_f3b3db_idx_and_more'),
        ('raw_materials', '0010_alter_clothcolor_hex_code_and_more'),
        ('tracking', '0015_alter_addahistory_change_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='addahistory',
            index=models.Index(fields=['-created_at'], name='tracking_ad_created_07b2e9_idx'),
        ),
    ]
