# Generated by Django 5.0.1 on 2026-07-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0051_backfill_default_streams'),
        ('tracking', '0016_addahistory_tracking_ad_created_07b2e9_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barcodebatch',
            unique_together={('adda', 'start_seq')},
        ),
    ]
