# Generated by Django 5.0.1 on 2026-07-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_barcode_append_ranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addahistory',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('stage_advanced', 'Stage Advanced'), ('stage_reopened', 'Stage Reopened'), ('status_changed', 'Status Changed'), ('roll_assigned', 'Roll Assigned'), ('roll_removed', 'Roll Removed'), ('completed', 'Completed'), ('cost_frozen', 'Cost Frozen'), ('stage_started', 'Stage Started'), ('workers_assigned', 'Workers Assigned'), ('bundle_created', 'Bundle Created'), ('barcodes_generated', 'Barcodes Generated'), ('exported', 'Exported'), ('settlement_finalized', 'Settlement Finalized'), ('settlement_reversed', 'Settlement Reversed'), ('settlement_superseded', 'Settlement Superseded'), ('completion_override', 'Completion Override'), ('verified_qty_corrected', 'Verified Qty Corrected'), ('report_voided', 'Report Voided'), ('stream_added', 'Cutting Lane Added'), ('stream_cancelled', 'Cutting Lane Cancelled')], max_length=32),
        ),
    ]
