"""P2 tests — geometry era: compute goldens (REAL isolated runtime),
calibration + geometry single-writer rules, immutability, units.

Golden strategy: synthetic ChArUco captures generated by the runtime's own
synth.py with KNOWN mm ground truth; the pipeline must measure them back
within the ADR-E tier. Real subprocess calls — the ADR-F bridge is part of
what P2 promises, so it is what P2 tests.
"""
import json
import shutil
import tempfile
import unittest
from pathlib import Path

from django.contrib.auth import get_user_model
from django.core.exceptions import PermissionDenied, ValidationError
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase, override_settings

from accounts.models import Role
from production.models import (Product, ProductPattern,
                               ProductPatternAssignment, ProductSize)
from patterns_ai.models import (CalibrationMat, CalibrationMatCheck,
                                CaptureAsset, GeometryExtraction,
                                PatternPieceVersion, PieceSizeGeometry)
from patterns_ai.services import calibration_service as cal
from patterns_ai.services import capture_service as cap
from patterns_ai.services import compute_bridge
from patterns_ai.services import pattern_geometry_service as geo
from patterns_ai.services.svg_render import geometry_svg
from patterns_ai.services.units import (mm_to_um, um_to_mm,
                                        validate_canonical_geometry)

User = get_user_model()
MEDIA = tempfile.mkdtemp(prefix='pai-p2-media-')
SYNTH_DIR = Path(tempfile.mkdtemp(prefix='pai-p2-golden-'))

# small fast board: 8x6 squares of 50 mm => 400x300 mm mat, 35 inner corners
BOARD = {'schema_version': 1, 'squares_x': 8, 'squares_y': 6,
         'square_mm': 50.0, 'marker_mm': 37.0,
         'aruco_dict': 'DICT_5X5_1000'}
# first inner-corner row has 7 corners: ids 0..6 span 6 squares = 300 mm
TAPE = {'schema_version': 1,
        'distances': [{'from_id': 0, 'to_id': 6, 'expected_mm': 300.0}]}
# ground-truth piece: 150x100 mm rectangle, inside the 20 mm keep-out
PIECE_MM = [[100, 80], [250, 80], [250, 180], [100, 180]]

RUNTIME_OK = compute_bridge.runtime_available()


def synth_golden(name, **over):
    """Render a golden capture via the runtime; returns PNG bytes."""
    out_img = SYNTH_DIR / f'{name}.png'
    job = {'board_spec': BOARD, 'out_image': str(out_img),
           'piece_polygon_mm': PIECE_MM, 'tilt': 0.06, 'yaw': 0.04,
           'blur': 1}
    job.update(over)
    res = compute_bridge.run_tool('synth', job)
    assert res['ok'], res
    return out_img.read_bytes()


@unittest.skipUnless(RUNTIME_OK, 'compute runtime venv missing — build per '
                                 'compute/patterns_ai/README.md (ADR-F). '
                                 'This suite REQUIRES it on dev machines.')
@override_settings(MEDIA_ROOT=MEDIA)
class _Base(TestCase):
    @classmethod
    def setUpTestData(cls):
        mgr = Role.objects.get_or_create(code='manager', defaults={'name': 'M'})[0]
        wk = Role.objects.get_or_create(code='worker', defaults={'name': 'W'})[0]
        cls.mgr = User.objects.create_user('p2@test.local', password='x', role=mgr)
        cls.worker = User.objects.create_user('p2w@test.local', password='x', role=wk)
        cls.product = Product.objects.create(code='P2PROD', name='P2 Product')
        cls.size_m = ProductSize.objects.create(product=cls.product, code='m',
                                                label='M', display_order=1)
        cls.size_l = ProductSize.objects.create(product=cls.product, code='l',
                                                label='L', display_order=2)
        cls.pattern = ProductPattern.objects.create(code='p2-front', name='Front')
        ProductPatternAssignment.objects.create(product=cls.product,
                                                pattern=cls.pattern,
                                                pieces_count=1)
        cls.other_product = Product.objects.create(code='P2OTHER', name='Other')
        cls.other_size = ProductSize.objects.create(
            product=cls.other_product, code='m', label='M')

    @classmethod
    def tearDownClass(cls):
        super().tearDownClass()
        shutil.rmtree(MEDIA, ignore_errors=True)

    def mat_active(self):
        mat = cal.register_mat(user=self.mgr, mat_code=f'MAT-{self.id().split(".")[-1][:12]}')
        mat, _ = cal.commission_mat(user=self.mgr, mat=mat, board_spec=BOARD,
                                    control_distances=TAPE)
        return mat

    def stored_capture(self, png_bytes, mat, product=None, name='cap.png'):
        return cap.store_capture(
            user=self.mgr, product=product or self.product,
            uploaded_file=SimpleUploadedFile(name, png_bytes, 'image/png'),
            source='camera', kind=CaptureAsset.Kind.PATTERN_CAPTURE, mat=mat)

    def piece(self):
        return geo.create_piece(user=self.mgr, product=self.product,
                                pattern=self.pattern, fabric_group='body')


class GoldenPipelineTests(_Base):
    """The headline promise: known-mm cardboard measured back honestly."""

    def test_golden_extraction_within_tier_and_canonical(self):
        mat = self.mat_active()
        capture = self.stored_capture(synth_golden('flat', tilt=0.06), mat)
        piece = self.piece()
        x = geo.run_extraction(user=self.mgr, capture=capture, piece=piece,
                               size=self.size_m)
        self.assertTrue(x.gate['passed'], x.gate)
        self.assertEqual(validate_canonical_geometry(x.geometry), [])
        w_mm = max(p[0] for p in x.geometry['outer']) / 1000
        h_mm = max(p[1] for p in x.geometry['outer']) / 1000
        # ADR-E in-cage tier: ±2 mm against tape truth (150 x 100)
        self.assertLess(abs(w_mm - 150), 2.0, f'width {w_mm}')
        self.assertLess(abs(h_mm - 100), 2.0, f'height {h_mm}')
        self.assertIn('composite', x.confidence)
        self.assertEqual(
            sorted(x.confidence['components']),
            ['board_coverage', 'residual', 'segmentation_stability',
             'self_check'])
        # provenance for reprocessing (ADR-D3): homography + pipeline stamp
        self.assertIn('homography', x.result['metrics'])
        self.assertEqual(x.pipeline_version, 'p2.1')

    def test_gate_refuses_boardless_photo_and_records_reasons(self):
        mat = self.mat_active()
        # a blank grey "photo" — no board anywhere (stored-mode zlib keeps it
        # over the 1 KB upload floor)
        import struct, zlib
        raw = b'\x00' + b'\x80' * 2000
        png = (b'\x89PNG\r\n\x1a\n'
               + _chunk(b'IHDR', struct.pack('>IIBBBBB', 2000, 1, 8, 0, 0, 0, 0))
               + _chunk(b'IDAT', zlib.compress(raw, 0))
               + _chunk(b'IEND', b''))
        capture = self.stored_capture(png, mat, name='blank.png')
        x = geo.run_extraction(user=self.mgr, capture=capture,
                               piece=self.piece(), size=self.size_m)
        self.assertFalse(x.gate['passed'])
        self.assertIsNone(x.geometry)
        self.assertTrue(any('board' in r for r in x.gate['reasons']))
        # the refusal is a RECORDED fact
        self.assertEqual(GeometryExtraction.objects.get(pk=x.pk).status,
                         'proposed')

    def test_extraction_gate_fails_on_bad_mat_tape(self):
        """Mat commissioned with wrong tape: the per-photo self-check refuses
        every capture — print-scale lies never become geometry."""
        mat = cal.register_mat(user=self.mgr, mat_code='MAT-BADTAPE')
        bad_tape = {'schema_version': 1, 'distances': [
            {'from_id': 0, 'to_id': 6, 'expected_mm': 320.0}]}
        cal.commission_mat(user=self.mgr, mat=mat, board_spec=BOARD,
                           control_distances=bad_tape)
        capture = self.stored_capture(synth_golden('badtape'), mat)
        x = geo.run_extraction(user=self.mgr, capture=capture,
                               piece=self.piece(), size=self.size_m)
        self.assertFalse(x.gate['passed'])
        self.assertTrue(any('self-check' in r for r in x.gate['reasons']))

    def test_dxf_round_trip_via_bridge(self):
        payload = {'schema_version': 1, 'units': 'um', 'origin': 'bbox_min',
                   'axes': 'x_right_y_up', 'chord_tolerance_um': 500,
                   'outer': [[0, 0], [150000, 0], [150000, 100000], [0, 100000]],
                   'holes': [],
                   'features': {'grain': {'angle_cdeg': 9000}, 'notches': [],
                                'drills': [], 'internal_lines': [],
                                'fold_edge': None, 'seam_allowance': 'as_cut'},
                   'grade_rule': None}
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / 'rt.dxf'
            res = compute_bridge.run_tool('dxf', {'op': 'export',
                                                  'geometry': payload,
                                                  'out_path': str(out)})
            self.assertTrue(res['ok'], res)
            res2 = compute_bridge.run_tool('dxf', {'op': 'import',
                                                   'dxf_path': str(out)})
        self.assertTrue(res2['ok'], res2)
        self.assertEqual(len(res2['pieces']), 1)
        rt = res2['pieces'][0]
        self.assertEqual(rt['outer'], payload['outer'])
        self.assertEqual(rt['features']['grain'], {'angle_cdeg': 9000})


def _chunk(tag, data):
    import struct, zlib
    return (struct.pack('>I', len(data)) + tag + data
            + struct.pack('>I', zlib.crc32(tag + data) & 0xffffffff))


class CalibrationServiceTests(_Base):
    def test_register_and_duplicate_refused(self):
        cal.register_mat(user=self.mgr, mat_code='MAT-A')
        with self.assertRaises(ValidationError):
            cal.register_mat(user=self.mgr, mat_code='MAT-A')
        with self.assertRaises(PermissionDenied):
            cal.register_mat(user=self.worker, mat_code='MAT-B')

    def test_commission_validations_and_lifecycle(self):
        mat = cal.register_mat(user=self.mgr, mat_code='MAT-C')
        with self.assertRaises(ValidationError):   # missing spec keys
            cal.commission_mat(user=self.mgr, mat=mat,
                               board_spec={'schema_version': 1},
                               control_distances=TAPE)
        with self.assertRaises(ValidationError):   # no distances
            cal.commission_mat(user=self.mgr, mat=mat, board_spec=BOARD,
                               control_distances={'schema_version': 1,
                                                  'distances': []})
        mat, check = cal.commission_mat(user=self.mgr, mat=mat,
                                        board_spec=BOARD,
                                        control_distances=TAPE)
        self.assertEqual(mat.status, 'active')
        self.assertTrue(check.passed)
        self.assertEqual(check.kind, 'commissioning')
        with self.assertRaises(ValidationError):   # only uncommissioned
            cal.commission_mat(user=self.mgr, mat=mat, board_spec=BOARD,
                               control_distances=TAPE)
        with self.assertRaises(ValidationError):   # retire needs reason
            cal.retire_mat(user=self.mgr, mat=mat, reason='  ')
        cal.retire_mat(user=self.mgr, mat=mat, reason='stretched')
        mat.refresh_from_db()
        self.assertEqual(mat.status, 'retired')

    def test_recheck_appends_evidence(self):
        mat = self.mat_active()
        capture = self.stored_capture(synth_golden('recheck'), mat)
        check = cal.record_recheck(user=self.mgr, mat=mat,
                                   photo_asset=capture)
        self.assertTrue(check.passed)
        self.assertEqual(check.kind, 'recheck')
        self.assertEqual(mat.checks.count(), 2)    # commissioning + recheck

    def test_mat_check_rows_are_append_only(self):
        mat = self.mat_active()
        check = mat.checks.first()
        check.notes = 'edited'
        with self.assertRaises(ValueError):
            check.save()
        with self.assertRaises(ValueError):
            check.delete()


class GeometryServiceTests(_Base):
    """Service rules with a FAKE bridge — shape-identical results, no
    subprocess cost; the REAL bridge is covered by GoldenPipelineTests."""

    FAKE_GEO = {'schema_version': 1, 'units': 'um', 'origin': 'bbox_min',
                'axes': 'x_right_y_up', 'chord_tolerance_um': 500,
                'outer': [[0, 0], [150000, 0], [150000, 100000], [0, 100000]],
                'holes': [],
                'features': {'grain': None, 'notches': [], 'drills': [],
                             'internal_lines': [], 'fold_edge': None,
                             'seam_allowance': 'as_cut'},
                'grade_rule': None}

    def fake_result(self, passed=True):
        return {'ok': True,
                'gate': {'passed': passed,
                         'reasons': [] if passed else ['tilt metric 0.5 '
                                                       'exceeds 0.35']},
                'metrics': {'corners_found': 30, 'corners_total': 35,
                            'corner_fraction': 0.857,
                            'residual_p95_mm': 0.05, 'tilt_metric': 0.02,
                            'homography': [[1, 0, 0], [0, 1, 0], [0, 0, 1]]},
                'checks': [],
                'segmentation': {'stability': 0.99, 'mask_area_mm2': 15000.0,
                                 'vertices': 4},
                'geometry': dict(self.FAKE_GEO) if passed else None,
                'confidence': {'components': {'board_coverage': 0.9,
                                              'residual': 0.95,
                                              'self_check': 1.0,
                                              'segmentation_stability': 0.99},
                               'composite': 90, 'note': 'x'},
                'provenance': {'pipeline_version': 'p2.1',
                               'backend': 'classical',
                               'params': {'chord_tolerance_um': 500,
                                          'px_per_mm': 2.0},
                               'available_backends': ['classical']}}

    def run_fake_extraction(self, piece=None, size=None, passed=True):
        from unittest import mock
        mat = self.mat_active()
        capture = self.stored_capture(b'\x89PNG\r\n\x1a\n' + b'\x03' * 4096,
                                      mat, name=f'f{passed}.png')
        piece = piece or self.piece()
        with mock.patch.object(compute_bridge, 'run_tool',
                               return_value=self.fake_result(passed)):
            return geo.run_extraction(user=self.mgr, capture=capture,
                                      piece=piece, size=size or self.size_m)

    def test_run_extraction_validations(self):
        mat = self.mat_active()
        piece = self.piece()
        marker_photo = cap.store_capture(
            user=self.mgr, product=self.product,
            uploaded_file=SimpleUploadedFile('m.png',
                                             b'\x89PNG\r\n\x1a\n' + b'\x05' * 2048,
                                             'image/png'),
            source='camera')                        # kind=marker_photo, no mat
        with self.assertRaises(ValidationError):    # wrong kind
            geo.run_extraction(user=self.mgr, capture=marker_photo,
                               piece=piece, size=self.size_m)
        pattern_cap = self.stored_capture(b'\x89PNG\r\n\x1a\n' + b'\x06' * 2048,
                                          mat, name='k.png')
        with self.assertRaises(ValidationError):    # cross-product size
            geo.run_extraction(user=self.mgr, capture=pattern_cap,
                               piece=piece, size=self.other_size)
        cal.retire_mat(user=self.mgr, mat=mat, reason='worn')
        with self.assertRaises(ValidationError):    # inactive mat
            geo.run_extraction(user=self.mgr, capture=pattern_cap,
                               piece=piece, size=self.size_m)

    def test_accept_creates_draft_row_and_is_one_shot(self):
        x = self.run_fake_extraction()
        row = geo.accept_extraction(user=self.mgr, extraction=x)
        self.assertEqual(row.version.status, 'draft')
        self.assertEqual(row.trust_grade, 'photo_calibrated')
        self.assertEqual(row.source_extraction_id, x.pk)
        x.refresh_from_db()
        self.assertEqual(x.status, 'accepted')
        with self.assertRaises(ValidationError):    # one-shot
            geo.accept_extraction(user=self.mgr, extraction=x)

    def test_accept_refused_when_gate_refused(self):
        x = self.run_fake_extraction(passed=False)
        with self.assertRaises(ValidationError):
            geo.accept_extraction(user=self.mgr, extraction=x)
        geo.reject_extraction(user=self.mgr, extraction=x, reason='blurry')
        x.refresh_from_db()
        self.assertEqual(x.status, 'rejected')
        with self.assertRaises(ValidationError):    # reject needs reason
            geo.reject_extraction(user=self.mgr,
                                  extraction=self.run_fake_extraction(passed=False),
                                  reason=' ')

    def test_extraction_rows_append_only(self):
        x = self.run_fake_extraction()
        x.backend = 'hacked'
        with self.assertRaises(ValueError):
            x.save()
        with self.assertRaises(ValueError):
            x.delete()

    def test_confirm_requires_grain_then_freezes(self):
        x = self.run_fake_extraction()
        row = geo.accept_extraction(user=self.mgr, extraction=x)
        version = row.version
        with self.assertRaises(ValidationError) as cm:
            geo.confirm_version(user=self.mgr, version=version)
        self.assertIn('grain', str(cm.exception))
        geo.confirm_version(user=self.mgr, version=version,
                            grain_by_size={self.size_m.pk: 9000})
        version.refresh_from_db()
        self.assertEqual(version.status, 'confirmed')
        row.refresh_from_db()
        self.assertEqual(row.geometry['features']['grain'],
                         {'angle_cdeg': 9000})
        # frozen: neither edit nor delete nor service-edit
        row.chord_tolerance_um = 400
        with self.assertRaises(ValueError):
            row.save()
        with self.assertRaises(ValueError):
            row.delete()
        with self.assertRaises(ValidationError):
            geo.edit_draft_geometry(user=self.mgr, version=version,
                                    size=self.size_m,
                                    outer_um=[[0, 0], [10, 0], [10, 10]])

    def test_tape_acceptance_upgrades_and_refuses(self):
        x = self.run_fake_extraction()
        row = geo.accept_extraction(user=self.mgr, extraction=x)
        with self.assertRaises(ValidationError) as cm:   # tape lies by 5 mm
            geo.confirm_version(
                user=self.mgr, version=row.version,
                grain_by_size={self.size_m.pk: 0},
                tape_by_size={self.size_m.pk: {'width_mm': 155,
                                               'height_mm': 100}})
        self.assertIn('tape', str(cm.exception))
        geo.confirm_version(
            user=self.mgr, version=row.version,
            grain_by_size={self.size_m.pk: 0},
            tape_by_size={self.size_m.pk: {'width_mm': 150.5,
                                           'height_mm': 99.8}})
        row.refresh_from_db()
        self.assertEqual(row.trust_grade, 'measured')
        self.assertEqual(row.tape_acceptance['delta_w_mm'], 0.5)

    def test_copy_forward_and_supersede(self):
        x = self.run_fake_extraction()
        row = geo.accept_extraction(user=self.mgr, extraction=x)
        v1 = row.version
        geo.confirm_version(user=self.mgr, version=v1,
                            grain_by_size={self.size_m.pk: 4500})
        v2 = geo.start_next_version(user=self.mgr, piece=v1.piece)
        self.assertEqual(v2.version_no, 2)
        carried = v2.size_geometries.get()
        row.refresh_from_db()          # confirm wrote grain into the row
        self.assertEqual(carried.copied_from_id, row.pk)
        self.assertEqual(carried.geometry, row.geometry)
        with self.assertRaises(ValidationError):    # one draft at a time
            geo.start_next_version(user=self.mgr, piece=v1.piece)
        geo.confirm_version(user=self.mgr, version=v2)  # grain carried
        v1.refresh_from_db()
        self.assertEqual(v1.status, 'superseded')
        self.assertEqual(v1.superseded_by_id, v2.pk)

    def test_edit_draft_geometry_rules(self):
        x = self.run_fake_extraction()
        row = geo.accept_extraction(user=self.mgr, extraction=x)
        # drag a vertex; give CW order — service must fix winding + re-anchor
        new_outer = [[1000, 1000], [1000, 101000], [151000, 101000],
                     [151000, 1000]]
        updated = geo.edit_draft_geometry(user=self.mgr, version=row.version,
                                          size=self.size_m,
                                          outer_um=new_outer,
                                          grain_cdeg=13500)
        self.assertEqual(min(p[0] for p in updated.geometry['outer']), 0)
        self.assertEqual(updated.geometry['features']['grain'],
                         {'angle_cdeg': 13500})
        self.assertEqual(validate_canonical_geometry(updated.geometry), [])
        with self.assertRaises(ValidationError):
            geo.edit_draft_geometry(user=self.mgr, version=row.version,
                                    size=self.size_m, outer_um=[[0, 0]])

    def test_import_dxf_via_real_bridge(self):
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / 'imp.dxf'
            res = compute_bridge.run_tool('dxf', {
                'op': 'export', 'geometry': self.FAKE_GEO,
                'out_path': str(out)})
            self.assertTrue(res['ok'])
            piece = self.piece()
            row = geo.import_dxf(user=self.mgr, piece=piece,
                                 size=self.size_m, dxf_path=out)
            with self.assertRaises(ValidationError):  # double import, same size
                geo.import_dxf(user=self.mgr, piece=piece, size=self.size_m,
                               dxf_path=out)
        self.assertEqual(row.trust_grade, 'uncalibrated')
        self.assertIsNone(row.source_extraction)
        self.assertEqual(row.geometry['outer'], self.FAKE_GEO['outer'])

    def test_set_label(self):
        label = geo.create_set_label(user=self.mgr, product=self.product,
                                     code='jul-2026', label='July set')
        with self.assertRaises(ValidationError):
            geo.create_set_label(user=self.mgr, product=self.product,
                                 code='jul-2026', label='dup')
        self.assertEqual(str(label.code), 'jul-2026')


class UnitsAndSvgTests(TestCase):
    def test_um_conversions(self):
        self.assertEqual(mm_to_um('150.0004'), 150000)
        self.assertEqual(mm_to_um('150.0006'), 150001)
        self.assertEqual(str(um_to_mm(150049)), '150.0')
        self.assertEqual(str(um_to_mm(150050)), '150.1')

    def test_validate_canonical(self):
        good = dict(GeometryServiceTests.FAKE_GEO)
        self.assertEqual(validate_canonical_geometry(good), [])
        bad = dict(good, outer=list(reversed(good['outer'])))
        self.assertTrue(any('winding' in p
                            for p in validate_canonical_geometry(bad)))
        closed = dict(good, outer=good['outer'] + [good['outer'][0]])
        self.assertTrue(any('closed' in p
                            for p in validate_canonical_geometry(closed)))
        offset = dict(good, outer=[[x + 5, y] for x, y in good['outer']])
        self.assertTrue(any('origin' in p
                            for p in validate_canonical_geometry(offset)))
        floats = dict(good, outer=[[0.5, 0], [10, 0], [10, 10]])
        self.assertTrue(any('non-integer' in p
                            for p in validate_canonical_geometry(floats)))
        self.assertEqual(validate_canonical_geometry({'schema_version': 99}),
                         ['schema_version missing or unsupported'])

    def test_svg_render(self):
        payload = dict(GeometryServiceTests.FAKE_GEO)
        payload['features'] = dict(payload['features'],
                                   grain={'angle_cdeg': 9000})
        svg = geometry_svg(payload, true_scale=True)
        self.assertIn('<svg', svg)
        # true-scale span = piece + 2x5 mm pad, matching the viewBox exactly
        # (mismatch = silent print shrink — the Gate-1 bug this pins against)
        self.assertIn('width="160.0mm"', svg)
        self.assertIn('viewBox="-5 -5 160.0 110.0"', svg)
        self.assertIn('pai-grain-arrow', svg)
        self.assertIn('data-w-mm="150.0"', svg)
        svg2 = geometry_svg(payload)
        self.assertIn('width="100%"', svg2)
