# Generated by Django 5.0.1 on 2026-01-11 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=100, unique=True)),
                ('cloth_type', models.CharField(choices=[('COTTON', 'Cotton'), ('HOSIERY', 'Hosiery'), ('POLYESTER', 'Polyester'), ('LINEN', 'Linen'), ('OTHER', 'Other')], max_length=20)),
                ('color', models.CharField(max_length=100)),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in inches/cm', max_digits=10)),
                ('gsm', models.IntegerField(blank=True, help_text='Grams per Square Meter', null=True)),
                ('total_length', models.DecimalField(decimal_places=2, help_text='Original length in meters', max_digits=10)),
                ('remaining_length', models.DecimalField(decimal_places=2, help_text='Current usable length', max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_per_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PARTIALLY_USED', 'Partially Used'), ('EXHAUSTED', 'Exhausted')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stage_type', models.CharField(choices=[('STORAGE', 'Storage (Warehouse)'), ('PROCESSING', 'Processing (Factory Floor)')], default='PROCESSING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling Price', max_digits=10),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(help_text='E.g. T-Shirt Order #102', max_length=255)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('WIP', 'Work In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_batches', to='inventory.stage')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.batch'),
        ),
        migrations.CreateModel(
            name='BatchClothAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_length', models.DecimalField(decimal_places=2, default=0, help_text='Planned usage', max_digits=10)),
                ('consumed_length', models.DecimalField(decimal_places=2, default=0, help_text='Actual usage', max_digits=10)),
                ('wastage_length', models.DecimalField(decimal_places=2, default=0, help_text='Wastage during cutting', max_digits=10)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CONSUMED', 'Consumed')], default='RESERVED', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloth_assignments', to='inventory.batch')),
                ('cloth_roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_assignments', to='inventory.clothroll')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('machine_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='inventory.stage')),
            ],
        ),
        migrations.AddField(
            model_name='clothroll',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloth_rolls', to='inventory.stage'),
        ),
        migrations.CreateModel(
            name='BatchOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('output_quantity', models.IntegerField(default=0, help_text='Qty processed in this session')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='inventory.batch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.machine')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stage')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ForeignKey(help_text='Warehouse Location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stage'),
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INWARD', 'Inward (Purchase)'), ('OUTWARD', 'Outward (Sale/Dispatch)'), ('CONSUMPTION', 'Consumption'), ('WASTAGE', 'Wastage'), ('TRANSFER', 'Transfer (Location Change)'), ('PRODUCTION', 'Production (Finished Goods)'), ('ADJUSTMENT', 'Adjustment')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Qty or Length', max_digits=10)),
                ('reference_note', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(blank=True, help_text='Context of movement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.batch')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outward_ledger', to='inventory.stage')),
                ('to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inward_ledger', to='inventory.stage')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BatchUserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('CUTTING_MASTER', 'Cutting Master'), ('KARIGAR', 'Karigar'), ('HELPER', 'Helper')], max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='inventory.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('batch', 'user', 'role')},
            },
        ),
    ]
