# Generated by Django 5.0.1 on 2026-01-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_clothroll_stage_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothroll',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Rama', 'Rama')], default='Red', max_length=20),
        ),
    ]
