# Generated by Django 5.0.1 on 2026-01-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_clothroll_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
