# Generated by Django 5.0.1 on 2026-01-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_batch_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothroll',
            name='exhaustion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Exhaustion Date'),
        ),
        migrations.AddField(
            model_name='clothroll',
            name='purchased_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchased Date'),
        ),
    ]
