# Generated by Django 5.0.1 on 2026-01-12 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_clothroll_exhaustion_date_clothroll_purchased_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothroll',
            name='batch_alloted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alloted_cloth_rolls', to='inventory.batch', verbose_name='Alloted Batch'),
        ),
    ]
