# Generated by Django 5.0.1 on 2026-04-02 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0006_clothroll_batch_alloted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('WIP', 'Work In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='batchclothassignment',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('CONSUMED', 'Consumed')], db_index=True, default='RESERVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='batchuserassignment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='batchuserassignment',
            name='role',
            field=models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('CUTTING_MASTER', 'Cutting Master'), ('KARIGAR', 'Karigar'), ('HELPER', 'Helper')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clothroll',
            name='cloth_type',
            field=models.CharField(choices=[('COTTON', 'Cotton'), ('HOSIERY', 'Hosiery'), ('POLYESTER', 'Polyester'), ('LINEN', 'Linen'), ('OTHER', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='clothroll',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PARTIALLY_USED', 'Partially Used'), ('EXHAUSTED', 'Exhausted')], db_index=True, default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='clothroll',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.CharField(choices=[('STORAGE', 'Storage (Warehouse)'), ('PROCESSING', 'Processing (Factory Floor)')], db_index=True, default='PROCESSING', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='transaction_type',
            field=models.CharField(choices=[('INWARD', 'Inward (Purchase)'), ('OUTWARD', 'Outward (Sale/Dispatch)'), ('CONSUMPTION', 'Consumption'), ('WASTAGE', 'Wastage'), ('TRANSFER', 'Transfer (Location Change)'), ('PRODUCTION', 'Production (Finished Goods)'), ('ADJUSTMENT', 'Adjustment')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['batch', 'transaction_type', '-date'], name='ledger_batch_type_date_idx'),
        ),
    ]
