# Generated by Django 5.0.1 on 2026-04-09 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_db_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchuserassignment',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='batchclothassignment',
            index=models.Index(fields=['batch', 'status'], name='batchcloth_batch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='batchuserassignment',
            constraint=models.UniqueConstraint(fields=('batch', 'user', 'role'), name='unique_batch_user_role'),
        ),
        migrations.AddConstraint(
            model_name='clothroll',
            constraint=models.CheckConstraint(check=models.Q(('remaining_length__gte', 0)), name='clothroll_remaining_nonneg'),
        ),
    ]
