# Generated by Django 5.0.1 on 2026-04-23 19:42

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_skill_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0008_alter_batchuserassignment_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStageMachineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_qty', models.PositiveIntegerField(default=0)),
                ('completed_qty', models.PositiveIntegerField(default=0)),
                ('wastage_qty', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='ASSIGNED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(help_text="Used in batch_number prefix e.g. '3patti'", max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BatchTypeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveIntegerField(help_text='1-based ordinal within the batch type workflow.')),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['batch_type', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Txn id / cheque no / UTR', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Received'), ('RECEIVED', 'Received'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='System roles (admin/manager/karigar) cannot be deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('dispatched_qty', models.PositiveIntegerField(default=0)),
                ('received_qty', models.PositiveIntegerField(default=0, help_text='Pieces confirmed by vendor on receipt.')),
                ('transit_wastage', models.PositiveIntegerField(default=0)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned')], db_index=True, default='SCHEDULED', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-dispatched_at', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='batch',
            name='final_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Final pieces produced after last stage.'),
        ),
        migrations.AddField(
            model_name='batch',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Target input pieces at batch start.'),
        ),
        migrations.AddField(
            model_name='batch',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchoperation',
            name='skill_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='accounts.skill'),
        ),
        migrations.AddField(
            model_name='batchoperation',
            name='wastage_quantity',
            field=models.IntegerField(default=0, help_text='Qty wasted in this session'),
        ),
        migrations.AddField(
            model_name='stage',
            name='category',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('LOGISTICS', 'Logistics'), ('FINANCIAL', 'Financial')], db_index=True, default='PRODUCTION', help_text='High-level lifecycle bucket for reporting and dashboards.', max_length=20),
        ),
        migrations.AddField(
            model_name='stage',
            name='code',
            field=models.SlugField(blank=True, help_text="Stable identifier used by services (e.g. 'stitching'). Auto-slugified from name if blank.", max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='default_is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(help_text='E.g. 3patti-2026-04-24', max_length=255),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('WIP', 'Work In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20),
        ),
        migrations.CreateModel(
            name='BatchStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveIntegerField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=20)),
                ('input_qty', models.PositiveIntegerField(default=0, help_text='Pieces entering this stage.')),
                ('output_qty', models.PositiveIntegerField(default=0, help_text='Pieces produced by this stage.')),
                ('wastage_qty', models.PositiveIntegerField(default=0, help_text='Pieces discarded at this stage.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='inventory.batch')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='inventory.stage')),
            ],
            options={
                'ordering': ['batch', 'sequence_order'],
            },
        ),
        migrations.AddField(
            model_name='batchoperation',
            name='batch_stage',
            field=models.ForeignKey(blank=True, help_text='Execution-layer link. Nullable for legacy rows predating BatchStage.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='inventory.batchstage'),
        ),
        migrations.AddIndex(
            model_name='batchoperation',
            index=models.Index(fields=['user', 'end_time'], name='op_user_endtime_idx'),
        ),
        migrations.AddIndex(
            model_name='batchoperation',
            index=models.Index(fields=['batch_stage', 'user'], name='op_bstage_user_idx'),
        ),
        migrations.AddField(
            model_name='batchstagemachineassignment',
            name='batch_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to='inventory.batchstage'),
        ),
        migrations.AddField(
            model_name='batchstagemachineassignment',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_assignments', to='inventory.machine'),
        ),
        migrations.AddField(
            model_name='batchstagemachineassignment',
            name='skill_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_assignments', to='accounts.skill'),
        ),
        migrations.AddField(
            model_name='batchstagemachineassignment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchtype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batch_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_type',
            field=models.ForeignKey(blank=True, help_text='Product category — determines the default stage sequence.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.batchtype'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status', '-created_at'], name='batch_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_type', 'status'], name='batch_type_status_idx'),
        ),
        migrations.AddField(
            model_name='batchtypestage',
            name='batch_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_templates', to='inventory.batchtype'),
        ),
        migrations.AddField(
            model_name='batchtypestage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_templates', to='inventory.stage'),
        ),
        migrations.AddField(
            model_name='batchtype',
            name='stages',
            field=models.ManyToManyField(help_text='Ordered default stages cloned onto each new batch of this type.', related_name='batch_types', through='inventory.BatchTypeStage', to='inventory.stage'),
        ),
        migrations.AddField(
            model_name='payment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.batch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='inventory_roles', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='vendordispatch',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='inventory.batch'),
        ),
        migrations.AddField(
            model_name='vendordispatch',
            name='batch_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='inventory.batchstage'),
        ),
        migrations.AddField(
            model_name='vendordispatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendordispatch',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='inventory.vendordispatch'),
        ),
        migrations.AddIndex(
            model_name='batchstage',
            index=models.Index(fields=['batch', 'status'], name='batchstage_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstage',
            index=models.Index(fields=['stage', 'status'], name='batchstage_stage_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='batchstage',
            constraint=models.UniqueConstraint(fields=('batch', 'sequence_order'), name='unique_batch_sequence'),
        ),
        migrations.AddConstraint(
            model_name='batchstage',
            constraint=models.UniqueConstraint(fields=('batch', 'stage'), name='unique_batch_stage'),
        ),
        migrations.AddConstraint(
            model_name='batchstage',
            constraint=models.CheckConstraint(check=models.Q(('input_qty__gte', django.db.models.expressions.CombinedExpression(models.F('output_qty'), '+', models.F('wastage_qty')))), name='batchstage_qty_reconciliation'),
        ),
        migrations.AddIndex(
            model_name='batchstagemachineassignment',
            index=models.Index(fields=['worker', 'status'], name='machasg_worker_status_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstagemachineassignment',
            index=models.Index(fields=['machine', 'status'], name='machasg_machine_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='batchstagemachineassignment',
            constraint=models.UniqueConstraint(fields=('batch_stage', 'machine', 'worker'), name='unique_stage_machine_worker'),
        ),
        migrations.AddConstraint(
            model_name='batchstagemachineassignment',
            constraint=models.CheckConstraint(check=models.Q(('assigned_qty__gte', django.db.models.expressions.CombinedExpression(models.F('completed_qty'), '+', models.F('wastage_qty')))), name='machineasg_qty_reconciliation'),
        ),
        migrations.AddConstraint(
            model_name='batchtypestage',
            constraint=models.UniqueConstraint(fields=('batch_type', 'stage'), name='unique_batchtype_stage'),
        ),
        migrations.AddConstraint(
            model_name='batchtypestage',
            constraint=models.UniqueConstraint(fields=('batch_type', 'sequence_order'), name='unique_batchtype_sequence'),
        ),
        migrations.AddIndex(
            model_name='vendordispatch',
            index=models.Index(fields=['batch', 'status'], name='dispatch_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordispatch',
            index=models.Index(fields=['vendor', 'status'], name='dispatch_vendor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['batch', 'status'], name='payment_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['vendor', 'status'], name='payment_vendor_status_idx'),
        ),
    ]
