# Generated by Django 5.0.1 on 2026-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_seed_accountant_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarItemRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(help_text="Django URL name, e.g. 'raw_materials:roll-list'.", max_length=128, unique=True)),
                ('section', models.CharField(help_text='Display section header.', max_length=64)),
                ('label', models.CharField(help_text='Display label in the sidebar.', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, help_text='Roles allowed to see this menu item.', related_name='visible_sidebar_items', to='inventory.role')),
            ],
            options={
                'ordering': ['section', 'label'],
            },
        ),
    ]
