# Generated by Django 5.0.1 on 2026-05-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_cutting_master_helper_skill'),
        ('inventory', '0015_seed_sidebar_item_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebaritemrule',
            name='allowed_skills',
            field=models.ManyToManyField(blank=True, help_text='Users with ANY of these skills also see this menu item.', related_name='visible_sidebar_items', to='accounts.skill'),
        ),
    ]
