# Generated by Django 5.0.1 on 2026-06-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_rename_karigar_role_to_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System roles (admin/manager/worker) cannot be deleted.'),
        ),
    ]
