# Generated by Django 5.0.1 on 2026-06-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_role_alter_user_extra_roles_alter_user_role_and_more'),
        ('inventory', '0020_alter_role_is_system'),
        ('production', '0028_alter_stage_access_by_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebaritemrule',
            name='allowed_roles',
        ),
        migrations.RemoveField(
            model_name='sidebaritemrule',
            name='allowed_skills',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='SidebarItemRule',
        ),
    ]
