# Generated by Django 5.0.1 on 2026-05-19 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_seed_default_workflow'),
        ('raw_materials', '0005_clothroll_adda_clothroll_used_at_clothroll_used_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddaStageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('adda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_records', to='production.adda')),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workers', models.ManyToManyField(blank=True, related_name='stage_assignments', to=settings.AUTH_USER_MODEL)),
                ('workflow_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.workflowstage')),
            ],
            options={
                'ordering': ['adda', 'workflow_stage__order'],
                'unique_together': {('adda', 'workflow_stage')},
            },
        ),
        migrations.CreateModel(
            name='LayeringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lay_count', models.PositiveIntegerField()),
                ('total_colors', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('rolls_used', models.ManyToManyField(related_name='layering_records', to='raw_materials.clothroll')),
                ('stage_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layering', to='production.addastagerecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
