# Generated by Django 5.0.1 on 2026-05-19 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_addastagerecord_layeringrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pieces_cut', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('stage_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cutting', to='production.addastagerecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
