# Generated by Django 5.0.1 on 2026-05-19 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_cuttingrecord'),
        ('raw_materials', '0005_clothroll_adda_clothroll_used_at_clothroll_used_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addastagerecord',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LayeringRollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('width_verified_inch', models.IntegerField(blank=True, null=True)),
                ('weight_verified_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('attached_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layering_entries', to='raw_materials.clothroll')),
                ('stage_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layering_roll_entries', to='production.addastagerecord')),
            ],
            options={
                'ordering': ['attached_at'],
                'unique_together': {('stage_record', 'roll')},
            },
        ),
    ]
