# Generated by Django 5.0.1 on 2026-05-20 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_layering_workspace'),
        ('raw_materials', '0006_update_width_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='layeringrollentry',
            name='layer_length_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='layeringrollentry',
            name='layers_on_roll',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RemainingClothOfClothRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remaining_weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remaining_length_meters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_consumed', models.BooleanField(default=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('consumed_in_adda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.adda')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('layering_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remaining_pieces', to='production.layeringrollentry')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remaining_pieces', to='raw_materials.clothroll')),
                ('source_adda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remaining_cloth_entries', to='production.adda')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['roll', 'is_consumed'], name='production__roll_id_8bf495_idx'), models.Index(fields=['source_adda'], name='production__source__082194_idx')],
            },
        ),
    ]
