# Generated by Django 5.0.1 on 2026-05-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_phase6_leftover_cloth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layeringrollentry',
            name='layer_length_meters',
        ),
        migrations.AddField(
            model_name='layeringrecord',
            name='layer_length_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
