# Generated by Django 5.0.1 on 2026-05-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_phase6_reshape_layer_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='addastagerecord',
            name='draft_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addastagerecord',
            name='draft_layer_length_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='addastagerecord',
            name='draft_notes',
            field=models.TextField(blank=True),
        ),
    ]
