# Generated by Django 5.0.1 on 2026-05-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_cutting_master_helper_skill'),
        ('inventory', '0013_seed_accountant_role'),
        ('production', '0008_phase6_draft_and_denormalized_leftover'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('layering', 'Layering'), ('cutting', 'Cutting')], help_text='Workflow stage this rule applies to (matches WorkflowStage.stage_type)', max_length=32, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, help_text='Users whose role (primary or extra) matches any of these can access.', related_name='stage_access_rules', to='inventory.role')),
                ('allowed_skills', models.ManyToManyField(blank=True, help_text='Users with ANY of these skills can access the stage.', related_name='stage_access_rules', to='accounts.skill')),
            ],
            options={
                'ordering': ['stage_type'],
            },
        ),
    ]
