# Generated by Django 5.0.1 on 2026-05-27 19:55

import django.db.models.deletion
import production.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_stage_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text="Stable identifier used in URLs/services (e.g. 'sleeve').", max_length=48, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='product_patterns/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='stage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CuttingPatternRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(upload_to=production.models._cutting_pattern_video_path)),
                ('notes', models.TextField(blank=True)),
                ('stage_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_pattern', to='production.addastagerecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuttingPatternPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=production.models._cutting_pattern_photo_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='production.cuttingpatternrecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPatternAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pieces_count', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_assignments', to='production.productpattern')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_assignments', to='production.product')),
            ],
            options={
                'ordering': ['product', 'pattern__name'],
                'unique_together': {('product', 'pattern')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='patterns',
            field=models.ManyToManyField(blank=True, related_name='products', through='production.ProductPatternAssignment', to='production.productpattern'),
        ),
    ]
