# Generated by Django 5.0.1 on 2026-05-27 20:21

import production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_seed_cutting_pattern_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingpatternrecord',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=production.models._cutting_pattern_video_path),
        ),
    ]
