# Generated by Django 5.0.1 on 2026-05-28 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_alter_cuttingpatternrecord_video'),
        ('raw_materials', '0008_phase6_draft_and_denormalized_leftover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=16)),
                ('label', models.CharField(max_length=40)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='production.product')),
            ],
            options={
                'ordering': ['product', 'display_order', 'code'],
                'unique_together': {('product', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CuttingPatternVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productpatternassignment')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.cuttingpatternphoto')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='production.cuttingpatternrecord')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assignment__pattern__name'],
                'unique_together': {('record', 'assignment')},
            },
        ),
        migrations.CreateModel(
            name='CuttingPieceBreakup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='raw_materials.clothcolor')),
                ('cutting_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakup', to='production.cuttingrecord')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productpattern')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='raw_materials.clothroll')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productsize')),
            ],
            options={
                'ordering': ['pattern__name', 'size__display_order', 'color__name'],
                'unique_together': {('cutting_record', 'size', 'color', 'pattern')},
            },
        ),
        migrations.CreateModel(
            name='CuttingPatternSizeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proportion_pct', models.PositiveSmallIntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_allocations', to='production.cuttingpatternrecord')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productsize')),
            ],
            options={
                'ordering': ['size__display_order', 'size__code'],
                'unique_together': {('record', 'size')},
            },
        ),
    ]
