# Generated by Django 5.0.1 on 2026-05-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_productsize_cuttingpatternverification_and_more'),
        ('raw_materials', '0008_phase6_draft_and_denormalized_leftover'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField()),
                ('bundle_number', models.CharField(blank=True, max_length=40)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='raw_materials.clothcolor')),
                ('cutting_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='production.cuttingrecord')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productpattern')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productsize')),
            ],
            options={
                'ordering': ['pattern__name', 'size__display_order', 'color__name', 'bundle_number'],
            },
        ),
    ]
