# Generated by Django 5.0.1 on 2026-05-28 17:14
# Rewritten 2026-05-29 to preserve legacy data (audit follow-up).
#
# YEH MIGRATION KYU HAI?
# ─────────────────────
# CuttingBundle restructure: pehle row = (cutting_record, pattern, color, count).
# Ab row = (cutting_record, size) header + CuttingBundleItem rows
# (pattern, color, count). Audit ne flag kiya: original migration ne
# (pattern, color, count) fields seedhe drop kar diye the — data preservation
# ke bina. Agar production mein CuttingBundle rows the to permanent loss.
#
# Rewrite: RunPython step add karke har existing CuttingBundle row se
# ek matching CuttingBundleItem row banao + total_pieces denormalise karo,
# phir purane fields drop. Forward-only — reverse path data restore nahi
# karta (intentional; old shape is lossy anyway).
#
# IMPORTANT (dev DB pe already-applied scenario):
# Yeh migration agar pehle applied ho chuki hai (purani destructive version),
# Django dobara nahi chalayega. RunPython idempotent likha hai — agar
# 'pattern' field already dropped hai (i.e. legacy state pre-rewrite) to
# RunPython quietly skip kar dega. Fresh prod deploys par data-preserving
# path chalega.

import django.db.models.deletion
from django.db import migrations, models


def _migrate_legacy_bundles_to_items(apps, schema_editor):
    """Old-shape rows (with pattern/color/count) → CuttingBundleItem rows.

    Idempotent + defensive: agar `pattern` field already drop ho chuka
    hai (legacy applied state) to skip — historical state was lost before.
    """
    CuttingBundle = apps.get_model('production', 'CuttingBundle')
    CuttingBundleItem = apps.get_model('production', 'CuttingBundleItem')

    # Schema introspection — agar pattern column nahi hai to RunPython skip.
    # Django ka historical model API columns reflect karta hai; getattr
    # safe pattern hai bagair raw SQL.
    if not hasattr(CuttingBundle._meta.get_field('id'), 'attname'):
        return
    field_names = {f.name for f in CuttingBundle._meta.get_fields()}
    if 'pattern' not in field_names or 'color' not in field_names or 'count' not in field_names:
        # Already applied old destructive version — legacy data gone, skip.
        return

    for bundle in CuttingBundle.objects.all():
        pattern_id = getattr(bundle, 'pattern_id', None)
        color_id = getattr(bundle, 'color_id', None)
        count_val = getattr(bundle, 'count', None)
        if not (pattern_id and color_id and count_val):
            continue
        # CuttingBundleItem row create — idempotent guard via unique_together.
        CuttingBundleItem.objects.get_or_create(
            bundle=bundle, pattern_id=pattern_id, color_id=color_id,
            defaults={'count': count_val},
        )
        # total_pieces denormalise — = legacy count for single-item legacy row.
        bundle.total_pieces = count_val
        bundle.save(update_fields=['total_pieces'])


def _noop_reverse(apps, schema_editor):
    """Reverse path nahi hai — data preservation forward-only.

    Old shape mein roll-back karna safe nahi: CuttingBundleItem (pattern,
    color, count) multi-row hota hai, CuttingBundle (pattern, color, count)
    single-row tha. Multi-row → single-row mapping lossy.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_cuttingbundle'),
        ('raw_materials', '0008_phase6_draft_and_denormalized_leftover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuttingbundle',
            options={'ordering': ['size__display_order', 'size__code']},
        ),
        migrations.AlterUniqueTogether(
            name='cuttingbundle',
            unique_together={('cutting_record', 'size')},
        ),
        migrations.AddField(
            model_name='cuttingbundle',
            name='total_pieces',
            field=models.PositiveIntegerField(default=0),
        ),
        # Create CuttingBundleItem BEFORE the data migration so the destination
        # table exists when we copy legacy bundle rows into it.
        migrations.CreateModel(
            name='CuttingBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField()),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.cuttingbundle')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='raw_materials.clothcolor')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productpattern')),
            ],
            options={
                'ordering': ['pattern__name', 'color__name'],
                'unique_together': {('bundle', 'pattern', 'color')},
            },
        ),
        # Data preservation: copy (pattern, color, count) from legacy bundles
        # into CuttingBundleItem rows + populate total_pieces. Idempotent.
        # Runs BEFORE the RemoveField operations below so the source columns
        # are still queryable.
        migrations.RunPython(
            _migrate_legacy_bundles_to_items,
            reverse_code=_noop_reverse,
        ),
        migrations.RemoveField(
            model_name='cuttingbundle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cuttingbundle',
            name='count',
        ),
        migrations.RemoveField(
            model_name='cuttingbundle',
            name='pattern',
        ),
    ]
