# Generated by Django 5.0.1 on 2026-05-28 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_cuttingbundle'),
        ('raw_materials', '0008_phase6_draft_and_denormalized_leftover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuttingbundle',
            options={'ordering': ['size__display_order', 'size__code']},
        ),
        migrations.AlterUniqueTogether(
            name='cuttingbundle',
            unique_together={('cutting_record', 'size')},
        ),
        migrations.AddField(
            model_name='cuttingbundle',
            name='total_pieces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='cuttingbundle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cuttingbundle',
            name='count',
        ),
        migrations.RemoveField(
            model_name='cuttingbundle',
            name='pattern',
        ),
        migrations.CreateModel(
            name='CuttingBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField()),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.cuttingbundle')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='raw_materials.clothcolor')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productpattern')),
            ],
            options={
                'ordering': ['pattern__name', 'color__name'],
                'unique_together': {('bundle', 'pattern', 'color')},
            },
        ),
    ]
