# Generated by Django 5.0.1 on 2026-05-28 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_alter_cuttingbundle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingbundleitem',
            name='source_breakup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumed_into', to='production.cuttingpiecebreakup'),
        ),
        migrations.AddField(
            model_name='cuttingpiecebreakup',
            name='consumed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
