# Generated by Django 5.0.1 on 2026-05-29 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_addastagerecord_indexes'),
        ('raw_materials', '0009_clothroll_adda_status_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPrintQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent to vendor'), ('received', 'Labels received'), ('printed', 'Printed (factory)'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AddaProductSizeColorPieceBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_piece_count', models.PositiveIntegerField()),
                ('adda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_color_breakdowns', to='production.adda')),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_color_breakdowns', to='production.cuttingbundle')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='raw_materials.clothcolor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cutting_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_color_breakdowns', to='production.cuttingrecord')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productsize')),
            ],
            options={
                'ordering': ['adda', 'size__display_order', 'color__name'],
            },
        ),
        migrations.CreateModel(
            name='BarcodeGenerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_barcodes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('stage_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_generation', to='production.addastagerecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
