# Generated by Django 5.0.1 on 2026-05-29 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_labelprintqueue_addaproductsizecolorpiecebreakdown_and_more'),
        ('tracking', '0009_barcodeexportbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelprintqueue',
            name='export_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_print_queue_rows', to='tracking.barcodeexportbatch'),
        ),
        migrations.AddIndex(
            model_name='addaproductsizecolorpiecebreakdown',
            index=models.Index(fields=['adda', 'size', 'color'], name='production__adda_id_8908d1_idx'),
        ),
        migrations.AddIndex(
            model_name='addaproductsizecolorpiecebreakdown',
            index=models.Index(fields=['cutting_record'], name='production__cutting_523d63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='addaproductsizecolorpiecebreakdown',
            unique_together={('cutting_record', 'size', 'color')},
        ),
        migrations.AddIndex(
            model_name='labelprintqueue',
            index=models.Index(fields=['status', '-created_at'], name='production__status_749fb2_idx'),
        ),
    ]
