# Generated by Django 5.0.1 on 2026-06-01 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_backfill_breakdown_for_completed_addas'),
    ]

    operations = [
        migrations.AddField(
            model_name='addastagerecord',
            name='cost_frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addastagerecord',
            name='cost_method_snapshot',
            field=models.CharField(blank=True, choices=[('per_piece', 'Per Piece'), ('per_bundle', 'Per Bundle'), ('per_layer', 'Per Layer'), ('fixed_cost', 'Fixed Cost')], max_length=16),
        ),
        migrations.AddField(
            model_name='addastagerecord',
            name='cost_quantity_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='addastagerecord',
            name='cost_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='addastagerecord',
            name='processing_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='default_cost_method',
            field=models.CharField(blank=True, choices=[('per_piece', 'Per Piece'), ('per_bundle', 'Per Bundle'), ('per_layer', 'Per Layer'), ('fixed_cost', 'Fixed Cost')], max_length=16),
        ),
        migrations.AddField(
            model_name='stage',
            name='default_cost_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='cost_billed_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_stages', to='production.workflowstage'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='cost_method',
            field=models.CharField(choices=[('per_piece', 'Per Piece'), ('per_bundle', 'Per Bundle'), ('per_layer', 'Per Layer'), ('fixed_cost', 'Fixed Cost')], default='per_piece', max_length=16),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='cost_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
