# Generated by Django 5.0.1 on 2026-06-01 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_rename_stage_access_sidebar_rule'),
        ('production', '0024_addastagerecord_cost_frozen_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStageRoleRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.role')),
                ('workflow_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_rates', to='production.workflowstage')),
            ],
            options={
                'ordering': ['workflow_stage', 'role__name'],
                'unique_together': {('workflow_stage', 'role')},
            },
        ),
    ]
