# Generated by Django 5.0.1 on 2026-06-06 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_accounts_us_is_acti_5e865e_idx_and_more'),
        ('inventory', '0019_rename_karigar_role_to_worker'),
        ('production', '0026_layering_cost_zero_grouped'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='addastagerecord',
            name='adda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_records', to='production.adda'),
        ),
        migrations.AddConstraint(
            model_name='addastagerecord',
            constraint=models.CheckConstraint(check=models.Q(('processing_cost__gte', 0)), name='prod_asr_processingcost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='addastagerecord',
            constraint=models.CheckConstraint(check=models.Q(('cost_rate_snapshot__gte', 0)), name='prod_asr_costrate_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='addastagerecord',
            constraint=models.CheckConstraint(check=models.Q(('cost_quantity_snapshot__gte', 0)), name='prod_asr_costqty_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='cuttingpatternsizeallocation',
            constraint=models.CheckConstraint(check=models.Q(('proportion_pct__lte', 100)), name='prod_sizealloc_pct_max100'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(check=models.Q(('default_cost_rate__gte', 0)), name='prod_stage_defaultrate_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.CheckConstraint(check=models.Q(('cost_rate__gte', 0)), name='prod_workflowstage_costrate_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='workflowstagerolerate',
            constraint=models.CheckConstraint(check=models.Q(('cost_rate__gte', 0)), name='prod_wsrolerate_costrate_nonneg'),
        ),
    ]
