# Generated by Django 5.0.1 on 2026-06-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_role_alter_user_extra_roles_alter_user_role_and_more'),
        ('production', '0027_alter_addastagerecord_adda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='access_by_role',
            field=models.ManyToManyField(blank=True, help_text='Users whose role (or extra_roles) matches any of these.', related_name='accessible_stages', to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='workflowstagerolerate',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.role'),
        ),
    ]
