# Generated by Django 5.0.1 on 2026-06-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0028_alter_stage_access_by_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstage',
            name='credits_workers',
            field=models.BooleanField(default=False),
        ),
    ]
