# Generated by Django 5.0.1 on 2026-06-09 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0030_seed_cutting_credits_workers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerStageTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='assigned', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('stage_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_tasks', to='production.addastagerecord')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stage_record', 'worker'],
                'indexes': [models.Index(fields=['stage_record'], name='production__stage_r_2673ff_idx'), models.Index(fields=['worker', 'status'], name='production__worker__72bb60_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workerstagetask',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('stage_record', 'worker'), name='uniq_active_worker_task_per_stage'),
        ),
        migrations.AddConstraint(
            model_name='workerstagetask',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['assigned', 'in_progress', 'completed', 'verified', 'cancelled'])), name='workerstagetask_status_valid'),
        ),
    ]
