# Generated by Django 5.0.1 on 2026-06-09 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0032_backfill_worker_tasks'),
        ('raw_materials', '0010_alter_clothcolor_hex_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerStageContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('verified_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('expected_earning', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bundle_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.cuttingbundleitem')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='raw_materials.clothcolor')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productsize')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='production.workerstagetask')),
            ],
            options={
                'ordering': ['task', 'pk'],
                'indexes': [models.Index(fields=['task'], name='production__task_id_1c412c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workerstagecontribution',
            constraint=models.CheckConstraint(check=models.Q(('reported_quantity__gt', 0)), name='wsc_reported_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='workerstagecontribution',
            constraint=models.CheckConstraint(check=models.Q(('verified_quantity__isnull', True), ('verified_quantity__gte', 0), _connector='OR'), name='wsc_verified_quantity_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='workerstagecontribution',
            constraint=models.CheckConstraint(check=models.Q(('expected_rate__isnull', True), ('expected_rate__gte', 0), _connector='OR'), name='wsc_expected_rate_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='workerstagecontribution',
            constraint=models.CheckConstraint(check=models.Q(('expected_earning__isnull', True), ('expected_earning__gte', 0), _connector='OR'), name='wsc_expected_earning_nonneg'),
        ),
    ]
