# Generated by Django 5.0.1 on 2026-06-11 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_addasettlementitem_and_more'),
        ('production', '0035_drop_worker_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstagecontribution',
            name='settlement_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settled_contributions', to='expense.stageworkassignment'),
        ),
    ]
