# Generated by Django 5.0.1 on 2026-06-14 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_seed_sidebar_rules'),
        ('production', '0036_workerstagecontribution_settlement_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstagecontribution',
            name='role_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.role'),
        ),
        migrations.CreateModel(
            name='AddaStageRoleRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.role')),
                ('stage_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_rates', to='production.addastagerecord')),
            ],
            options={
                'ordering': ['stage_record', 'role__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='addastagerolerate',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 0)), name='prod_addastagerolerate_rate_nonneg'),
        ),
        migrations.AlterUniqueTogether(
            name='addastagerolerate',
            unique_together={('stage_record', 'role')},
        ),
    ]
