# Generated by Django 5.0.1 on 2026-06-14 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_seed_sidebar_rules'),
        ('production', '0037_workerstagecontribution_role_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCorrectionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('new_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('recalc_count', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.role')),
                ('stage_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_corrections', to='production.addastagerecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='ratecorrectionaudit',
            constraint=models.CheckConstraint(check=models.Q(('old_rate__gte', 0), ('new_rate__gte', 0)), name='prod_ratecorrection_rates_nonneg'),
        ),
    ]
