# Generated by Django 5.0.1 on 2026-06-14 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0040_workflowstage_allocation_dimensions'),
        ('raw_materials', '0010_alter_clothcolor_hex_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagePoolSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('good', models.DecimalField(decimal_places=2, max_digits=12)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='raw_materials.clothcolor')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productsize')),
                ('stage_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_snapshots', to='production.addastagerecord')),
            ],
            options={
                'ordering': ['stage_record', 'color', 'size'],
            },
        ),
        migrations.AddConstraint(
            model_name='stagepoolsnapshot',
            constraint=models.CheckConstraint(check=models.Q(('good__gte', 0)), name='prod_stagepoolsnapshot_good_nonneg'),
        ),
        migrations.AlterUniqueTogether(
            name='stagepoolsnapshot',
            unique_together={('stage_record', 'color', 'size')},
        ),
    ]
