# Generated by Django 5.0.1 on 2026-06-14 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0041_stagepoolsnapshot'),
        ('raw_materials', '0010_alter_clothcolor_hex_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerStageAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='raw_materials.clothcolor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productsize')),
                ('stage_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_allocations', to='production.addastagerecord')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stage_record', 'worker', 'pk'],
                'indexes': [models.Index(fields=['stage_record', 'worker'], name='production__stage_r_aa0902_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workerstageallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocated_quantity__gt', 0)), name='prod_workerstageallocation_qty_positive'),
        ),
    ]
