# Generated by Django 5.0.1 on 2026-07-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0043_rename_pattern_design_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingpatternrecord',
            name='lead_minutes_from_layering',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
