# Generated by Django 5.0.1 on 2026-07-05 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_seed_sidebar_rules'),
        ('production', '0044_cuttingpatternrecord_lead_minutes_from_layering'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'stage categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='work_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('machine', 'Machine')], default='manual', help_text='HOW the operation is performed. Machine ⇒ pick a Machine Type.', max_length=16),
        ),
        migrations.AddField(
            model_name='stage',
            name='machine_type',
            field=models.ForeignKey(blank=True, help_text='Mandatory when Work Type = Machine; forbidden when Manual.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='production.machinetype'),
        ),
        migrations.AddField(
            model_name='stage',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Grouping for dashboards/reports ONLY — never workflow logic.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='production.stagecategory'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('machine_type__isnull', False), ('work_type', 'machine')), models.Q(models.Q(('work_type', 'machine'), _negated=True), ('machine_type__isnull', True)), _connector='OR'), name='prod_stage_worktype_machinetype_pair'),
        ),
    ]
