# Generated by Django 5.0.1 on 2026-07-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0046_r10_seed_categories_worktypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
