# Generated by Django 5.0.1 on 2026-07-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_worker_sidebar_lockdown'),
        ('expense', '0014_payrollsettlementitem_write_off_reason_and_more'),
        ('production', '0047_r10c_stagecategory_is_active'),
        ('raw_materials', '0010_alter_clothcolor_hex_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workerstagecontribution',
            name='wsc_gam_nonneg_sum_positive',
        ),
        migrations.AddField(
            model_name='workerstagecontribution',
            name='damaged_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='workerstagecontribution',
            name='machine_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='workerstagetask',
            name='first_report_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='workerstagecontribution',
            constraint=models.CheckConstraint(check=models.Q(('good_quantity__gte', 0), ('alter_quantity__gte', 0), ('missing_quantity__gte', 0), ('damaged_quantity__gte', 0), models.Q(('good_quantity__gt', 0), ('alter_quantity__gt', 0), ('missing_quantity__gt', 0), ('damaged_quantity__gt', 0), _connector='OR')), name='wsc_gamd_nonneg_sum_positive'),
        ),
    ]
