# Generated by Django 5.0.1 on 2026-07-06 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0048_pre_phase3_scrap_machine_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='addastagerecord',
            index=models.Index(fields=['completed_at', 'started_at'], name='production__complet_f3b3db_idx'),
        ),
        migrations.AddIndex(
            model_name='workerstagetask',
            index=models.Index(fields=['status', 'created_at'], name='production__status_e315b3_idx'),
        ),
    ]
