# Generated by Django 5.0.1 on 2026-07-11 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0049_addastagerecord_production__complet_f3b3db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabric_group', models.CharField(max_length=32)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('is_blocking', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['adda', 'fabric_group', 'sequence'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='addastagerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cuttingbundle',
            name='adda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to='production.adda'),
        ),
        migrations.AlterField(
            model_name='cuttingbundle',
            name='cutting_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='production.cuttingrecord'),
        ),
        migrations.AddConstraint(
            model_name='cuttingbundle',
            constraint=models.UniqueConstraint(condition=models.Q(('cutting_record__isnull', True)), fields=('adda', 'size'), name='prod_bundle_unique_adda_size'),
        ),
        migrations.AddField(
            model_name='cuttingstream',
            name='adda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_streams', to='production.adda'),
        ),
        migrations.AddField(
            model_name='cuttingstream',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addastagerecord',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage_records', to='production.cuttingstream'),
        ),
        migrations.AddConstraint(
            model_name='cuttingstream',
            constraint=models.UniqueConstraint(fields=('adda', 'fabric_group', 'sequence'), name='prod_stream_unique_lane'),
        ),
        migrations.AddConstraint(
            model_name='cuttingstream',
            constraint=models.CheckConstraint(check=models.Q(('sequence', 1), models.Q(('reason', ''), _negated=True), _connector='OR'), name='prod_stream_declared_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='cuttingstream',
            constraint=models.CheckConstraint(check=models.Q(('cancelled_at__isnull', True), models.Q(('cancel_reason', ''), _negated=True), _connector='OR'), name='prod_stream_cancel_requires_reason'),
        ),
    ]
