# Generated by Django 5.0.1 on 2026-07-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0051_backfill_default_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstageallocation',
            name='allocation_mode',
            field=models.CharField(choices=[('whole', 'Whole bundle'), ('partial', 'Partial')], default='partial', max_length=8),
        ),
    ]
