# Generated by Django 5.0.1 on 2026-06-01 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0024_addastagerecord_cost_frozen_at_and_more'),
        ('raw_materials', '0009_clothroll_adda_status_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageWorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('earning_rate_snapshot', models.DecimalField(decimal_places=4, max_digits=10)),
                ('earning_amount_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.cuttingbundle')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='raw_materials.clothcolor')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productsize')),
                ('stage_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_assignments', to='production.addastagerecord')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='advances/')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-advance_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('upi', 'UPI'), ('other', 'Other')], default='cash', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=8)),
                ('category', models.CharField(choices=[('stage_earning', 'Stage Earning'), ('production_earning', 'Production Earning'), ('advance', 'Advance'), ('payment', 'Payment'), ('deduction', 'Deduction'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='expense.workeradvance')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='expense.stageworkassignment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='expense.workerledgerentry')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='expense.workerpayment')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_all_payroll', 'Can view all workers payroll'), ('manage_advances', 'Can record worker advances'), ('manage_payments', 'Can record worker payments')],
            },
        ),
        migrations.AddIndex(
            model_name='stageworkassignment',
            index=models.Index(fields=['worker', '-created_at'], name='expense_sta_worker__a73768_idx'),
        ),
        migrations.AddIndex(
            model_name='stageworkassignment',
            index=models.Index(fields=['stage_record'], name='expense_sta_stage_r_541d02_idx'),
        ),
        migrations.AddIndex(
            model_name='workeradvance',
            index=models.Index(fields=['worker', '-advance_date'], name='expense_wor_worker__cf4e94_idx'),
        ),
        migrations.AddIndex(
            model_name='workerpayment',
            index=models.Index(fields=['worker', '-payment_date'], name='expense_wor_worker__be2e87_idx'),
        ),
        migrations.AddIndex(
            model_name='workerledgerentry',
            index=models.Index(fields=['worker', '-created_at'], name='expense_wor_worker__e9b517_idx'),
        ),
        migrations.AddIndex(
            model_name='workerledgerentry',
            index=models.Index(fields=['worker', 'entry_type'], name='expense_wor_worker__8e9d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='workerledgerentry',
            index=models.Index(fields=['worker', 'category'], name='expense_wor_worker__52da4d_idx'),
        ),
    ]
