# Generated by Django 5.0.1 on 2026-06-01 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        ('production', '0024_addastagerecord_cost_frozen_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageworkassignment',
            name='bundle_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_assignments', to='production.cuttingbundleitem'),
        ),
        migrations.AddField(
            model_name='stageworkassignment',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productpattern'),
        ),
        migrations.AddField(
            model_name='stageworkassignment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
