# Generated by Django 5.0.1 on 2026-06-06 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_settlement_models'),
        ('production', '0026_layering_cost_zero_grouped'),
        ('raw_materials', '0009_clothroll_adda_status_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workeradvance',
            index=models.Index(fields=['advance_date'], name='expense_wor_advance_e2d969_idx'),
        ),
        migrations.AddIndex(
            model_name='workerledgerentry',
            index=models.Index(fields=['worker', 'entry_date'], name='expense_wor_worker__6c8504_idx'),
        ),
        migrations.AddIndex(
            model_name='workerledgerentry',
            index=models.Index(fields=['entry_date'], name='expense_wor_entry_d_929c99_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollsettlement',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__gte', 0)), name='expense_settlement_paid_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='payrollsettlement',
            constraint=models.CheckConstraint(check=models.Q(('advance_deducted__gte', 0)), name='expense_settlement_advdeducted_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='payrollsettlement',
            constraint=models.CheckConstraint(check=models.Q(('payable_before__gte', 0)), name='expense_settlement_payablebefore_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='payrollsettlement',
            constraint=models.CheckConstraint(check=models.Q(('advance_outstanding_before__gte', 0)), name='expense_settlement_advoutstanding_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='payrollsettlementitem',
            constraint=models.CheckConstraint(check=models.Q(('amount_recovered__gt', 0)), name='expense_settlementitem_recovered_positive'),
        ),
        migrations.AddConstraint(
            model_name='stageworkassignment',
            constraint=models.CheckConstraint(check=models.Q(('allocated_quantity__gt', 0)), name='expense_swa_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stageworkassignment',
            constraint=models.CheckConstraint(check=models.Q(('earning_rate_snapshot__gte', 0)), name='expense_swa_rate_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='stageworkassignment',
            constraint=models.CheckConstraint(check=models.Q(('earning_amount_snapshot__gte', 0)), name='expense_swa_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='workeradvance',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='expense_advance_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='workerledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='expense_ledgerentry_amount_positive'),
        ),
    ]
