# Generated by Django 5.0.1 on 2026-06-06 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_workeradvance_expense_wor_advance_e2d969_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettlementitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollsettlementitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
