# Generated by Django 5.0.1 on 2026-06-11 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_payrollsettlementitem_created_at_and_more'),
        ('production', '0035_drop_worker_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddaSettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_earning', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_outstanding_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('packed_quantity', models.PositiveIntegerField(default=0)),
                ('missing_quantity', models.PositiveIntegerField(default=0)),
                ('rejected_quantity', models.PositiveIntegerField(default=0)),
                ('alter_quantity', models.PositiveIntegerField(default=0)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payrollsettlementitem',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='expense.payrollsettlement'),
        ),
        migrations.CreateModel(
            name='AddaSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('reversed', 'Reversed'), ('superseded', 'Superseded')], default='draft', max_length=12)),
                ('variance_policy', models.CharField(choices=[('factory_absorbs', 'Factory absorbs')], default='factory_absorbs', max_length=24)),
                ('expected_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('packed_total', models.PositiveIntegerField(default=0)),
                ('missing_total', models.PositiveIntegerField(default=0)),
                ('rejected_total', models.PositiveIntegerField(default=0)),
                ('alter_total', models.PositiveIntegerField(default=0)),
                ('variance_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('adda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='production.adda')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='expense.addasettlement')),
            ],
        ),
        migrations.AddField(
            model_name='payrollsettlementitem',
            name='adda_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recovery_lines', to='expense.addasettlement'),
        ),
        migrations.AddConstraint(
            model_name='payrollsettlementitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('adda_settlement__isnull', True), ('settlement__isnull', False)), models.Q(('adda_settlement__isnull', False), ('settlement__isnull', True)), _connector='OR'), name='expense_settlementitem_exactly_one_parent'),
        ),
        migrations.AddField(
            model_name='addasettlementitem',
            name='adda_settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='expense.addasettlement'),
        ),
        migrations.AddField(
            model_name='addasettlementitem',
            name='earning_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='expense.stageworkassignment'),
        ),
        migrations.AddField(
            model_name='addasettlementitem',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addasettlementitem',
            name='stage_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.addastagerecord'),
        ),
        migrations.AddField(
            model_name='addasettlementitem',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='addasettlement',
            index=models.Index(fields=['adda', '-settled_at'], name='expense_add_adda_id_37f789_idx'),
        ),
        migrations.AddConstraint(
            model_name='addasettlement',
            constraint=models.CheckConstraint(check=models.Q(('expected_total__gte', 0), ('variance_total__gte', 0)), name='expense_addasettlement_totals_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='addasettlement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'finalized'), _negated=True), ('settled_at__isnull', False), _connector='OR'), name='expense_addasettlement_finalized_has_settled_at'),
        ),
        migrations.AddIndex(
            model_name='addasettlementitem',
            index=models.Index(fields=['adda_settlement', 'worker'], name='expense_add_adda_se_2c9f92_idx'),
        ),
        migrations.AddConstraint(
            model_name='addasettlementitem',
            constraint=models.CheckConstraint(check=models.Q(('expected_earning__gte', 0), ('advance_outstanding_before__gte', 0), ('advance_recovered__gte', 0), ('final_payable__gte', 0), ('variance_amount__gte', 0)), name='expense_addasettlementitem_amounts_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='addasettlementitem',
            constraint=models.CheckConstraint(check=models.Q(('advance_recovered__lte', models.F('advance_outstanding_before'))), name='expense_addasettlementitem_recovery_within_outstanding'),
        ),
    ]
