# Generated by Django 5.0.1 on 2026-06-11 10:30

import django.db.models.deletion
from django.db import migrations, models


def backfill_settlement_swa_links(apps, schema_editor):
    """Known-facts backfill: PR-B-era settlement SWAs carry the deterministic
    note 'settled via ADST-XXXX' written at finalize — link them structurally.
    Also backfill PSI.ledger_entry for ADST-parented recovery lines via the
    note written by the same finalize (none exist on dev; future-safe)."""
    AddaSettlement = apps.get_model('expense', 'AddaSettlement')
    SWA = apps.get_model('expense', 'StageWorkAssignment')
    refs = {a.reference: a.pk for a in AddaSettlement.objects.all()}
    for swa in SWA.objects.filter(adda_settlement__isnull=True,
                                  notes__startswith='settled via '):
        ref = swa.notes.replace('settled via ', '').strip()
        if ref in refs:
            swa.adda_settlement_id = refs[ref]
            swa.save(update_fields=['adda_settlement'])


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_addasettlementitem_and_more'),
    ]

    operations = [
        # Fields first; the known-facts backfill (note-derived links) runs last.
        migrations.AddField(
            model_name='payrollsettlementitem',
            name='ledger_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='expense.workerledgerentry'),
        ),
        migrations.AddField(
            model_name='payrollsettlementitem',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stageworkassignment',
            name='adda_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='earning_lines', to='expense.addasettlement'),
        ),
        migrations.RunPython(backfill_settlement_swa_links,
                             migrations.RunPython.noop),
    ]