# Generated by Django 5.0.1 on 2026-06-14 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_payrollsettlementitem_ledger_entry_and_more'),
        ('production', '0038_ratecorrectionaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementReconciliationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.CharField(max_length=32)),
                ('output_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('allocated_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty_delta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('adda_settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_evidence', to='expense.addasettlement')),
                ('stage_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.addastagerecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['flag', 'created_at'], name='expense_set_flag_81595b_idx')],
            },
        ),
    ]
