# Generated by Django 5.0.1 on 2026-07-04 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0011_reconciliation_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='pay_basis',
            field=models.CharField(choices=[('piece_rate', 'Piece Rate'), ('monthly', 'Monthly Salary')], default='piece_rate', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkerPayBasisAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_basis', models.CharField(choices=[('piece_rate', 'Piece Rate'), ('monthly', 'Monthly Salary')], max_length=20)),
                ('new_basis', models.CharField(choices=[('piece_rate', 'Piece Rate'), ('monthly', 'Monthly Salary')], max_length=20)),
                ('unsettled_lines_at_change', models.PositiveIntegerField(default=0)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_basis_changes_made', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_basis_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
