# Generated by Django 5.0.1 on 2026-07-04 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0013_factoryexpense_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettlementitem',
            name='write_off_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payrollsettlementitem',
            name='written_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advance_write_offs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='payrollsettlementitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('write_off_reason', ''), ('written_off_by__isnull', True)), models.Q(models.Q(('write_off_reason', ''), _negated=True), ('written_off_by__isnull', False)), _connector='OR'), name='expense_settlementitem_writeoff_coherent'),
        ),
    ]
