# Generated by Django 5.0.1 on 2026-07-18 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0014_payrollsettlementitem_write_off_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity'), ('salary', 'Salary'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_templates_created', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseGenerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_key', models.CharField(max_length=20)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('regeneration_reason', models.CharField(blank=True, max_length=200)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generation_record', to='expense.factoryexpense')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_generations_triggered', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='expense.expensegenerationrecord')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_records', to='expense.expensetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseTemplateAmountAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=200)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_template_amount_changes', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amount_audits', to='expense.expensetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='expensetemplate',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='expensetemplate_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expensetemplate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('category', 'salary'), ('worker__isnull', False)), models.Q(models.Q(('category', 'salary'), _negated=True), ('worker__isnull', True)), _connector='OR'), name='expensetemplate_salary_iff_worker'),
        ),
        migrations.AddConstraint(
            model_name='expensetemplate',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='expensetemplate_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='expensetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('category', 'salary'), ('is_active', True)), fields=('worker',), name='expensetemplate_one_active_salary_per_worker'),
        ),
        migrations.AddIndex(
            model_name='expensegenerationrecord',
            index=models.Index(fields=['template', 'period_key'], name='expense_exp_templat_67a69e_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensegenerationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('superseded_at__isnull', True)), fields=('template', 'period_key'), name='expensegeneration_one_current_per_period'),
        ),
        migrations.AddConstraint(
            model_name='expensegenerationrecord',
            constraint=models.CheckConstraint(check=models.Q(('supersedes__isnull', True), models.Q(('regeneration_reason', ''), _negated=True), _connector='OR'), name='expensegeneration_regen_needs_reason'),
        ),
        migrations.AddConstraint(
            model_name='expensetemplateamountaudit',
            constraint=models.CheckConstraint(check=models.Q(('reason', ''), _negated=True), name='expenseamountaudit_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='expensetemplateamountaudit',
            constraint=models.CheckConstraint(check=models.Q(('old_amount', models.F('new_amount')), _negated=True), name='expenseamountaudit_amounts_differ'),
        ),
        migrations.AddConstraint(
            model_name='expensetemplateamountaudit',
            constraint=models.CheckConstraint(check=models.Q(('new_amount__gt', 0), ('old_amount__gt', 0)), name='expenseamountaudit_amounts_positive'),
        ),
    ]
