# Generated by Django 5.0.1 on 2026-07-31 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='learning_one_bookmark_per_user_chapter',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='kind',
            field=models.CharField(choices=[('bookmark', 'Bookmark'), ('favourite', 'Favourite')], default='bookmark', max_length=16),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='scroll_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='seconds_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'course_slug', 'chapter_slug', 'kind'), name='learning_one_mark_per_user_chapter_kind'),
        ),
    ]
