# Generated by Django 5.0.1 on 2026-05-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0002_seed_master_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roll_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('purchased_date', models.DateField()),
                ('width_inch', models.IntegerField(blank=True, choices=[(36, '36"'), (37, '37"'), (38, '38"'), (39, '39"'), (40, '40"'), (41, '41"'), (42, '42"'), (43, '43"'), (44, '44"')], null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('cost_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('not_used', 'Not Used'), ('used', 'Used')], default='not_used', max_length=16)),
                ('cloth_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='raw_materials.clothcolor')),
                ('cloth_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='raw_materials.clothtype')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='raw_materials.storagelocation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='raw_materia_status_7d3cdd_idx'), models.Index(fields=['cloth_type', 'cloth_color'], name='raw_materia_cloth_t_b31823_idx'), models.Index(fields=['storage_location', 'status'], name='raw_materia_storage_54a301_idx')],
            },
        ),
    ]
