# Generated by Django 5.0.1 on 2026-05-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0005_clothroll_adda_clothroll_used_at_clothroll_used_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothroll',
            name='width_inch',
            field=models.IntegerField(blank=True, choices=[(36, '36 inch'), (37, '37 inch'), (38, '38 inch'), (39, '39 inch'), (40, '40 inch'), (41, '41 inch'), (42, '42 inch'), (43, '43 inch'), (44, '44 inch')], null=True),
        ),
    ]
