# Generated by Django 5.0.1 on 2026-05-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0006_update_width_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothroll',
            name='layer_length_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='clothroll',
            name='layers_on_roll',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
