# Generated by Django 5.0.1 on 2026-05-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0007_phase6_reshape_layer_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothroll',
            name='remaining_length_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='clothroll',
            name='remaining_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
