# Generated by Django 5.0.1 on 2026-06-06 09:49

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_alter_addastagerecord_adda_and_more'),
        ('raw_materials', '0009_clothroll_adda_status_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothcolor',
            name='hex_code',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour like #AABBCC.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddConstraint(
            model_name='clothcolor',
            constraint=models.CheckConstraint(check=models.Q(('hex_code', ''), ('hex_code__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='rawmat_clothcolor_hex_format'),
        ),
        migrations.AddConstraint(
            model_name='clothroll',
            constraint=models.CheckConstraint(check=models.Q(('cost_per_kg__gte', 0)), name='rawmat_clothroll_costperkg_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='clothroll',
            constraint=models.CheckConstraint(check=models.Q(('weight_kg__gte', 0)), name='rawmat_clothroll_weight_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='clothroll',
            constraint=models.CheckConstraint(check=models.Q(('remaining_length_meters__gte', 0)), name='rawmat_clothroll_remlen_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='clothroll',
            constraint=models.CheckConstraint(check=models.Q(('remaining_weight_kg__gte', 0)), name='rawmat_clothroll_remwt_nonneg'),
        ),
    ]
