# Generated by Django 5.0.1 on 2026-07-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0010_alter_clothcolor_hex_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothroll',
            name='is_one_way_nap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clothroll',
            name='selvedge_note',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='clothroll',
            name='stretch_class',
            field=models.CharField(blank=True, choices=[('none', 'No stretch'), ('two_way', '2-way'), ('four_way', '4-way')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clothroll',
            name='usable_width_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Human-confirmed usable lay width (mm) for marker planning.', null=True),
        ),
    ]
