# Generated by Django 5.0.1 on 2026-07-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0011_clothroll_is_one_way_nap_clothroll_selvedge_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothroll',
            name='status',
            field=models.CharField(choices=[('not_used', 'Not Used'), ('used', 'Used'), ('damaged', 'Damaged')], default='not_used', max_length=16),
        ),
    ]
