# Generated by Django 5.0.1 on 2026-07-05 13:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0046_r10_seed_categories_worktypes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='production.machinetype')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MachineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('adda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_assignments', to='production.adda')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='machines.machine')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'inactive', 'maintenance'])), name='machines_machine_status_enum'),
        ),
        migrations.AddConstraint(
            model_name='machineassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_at__isnull', True)), fields=('machine',), name='machines_one_open_assignment_per_machine'),
        ),
        migrations.AddConstraint(
            model_name='machineassignment',
            constraint=models.CheckConstraint(check=models.Q(('end_at__isnull', True), ('end_at__gte', models.F('start_at')), _connector='OR'), name='machines_assignment_window_valid'),
        ),
    ]
