# Generated by Django 5.0.1 on 2026-04-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. T-Shirts, Pants & Trousers', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text="Short description shown below the name (e.g. 'Round neck, V-neck, Polo — all styles')", max_length=200)),
                ('item_count_label', models.CharField(default='50+ Items', help_text="Badge shown on the card (e.g. '120+ Items')", max_length=50)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG markup for the category icon. Leave blank for default icon.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Link text', max_length=100)),
                ('url', models.CharField(help_text="URL or anchor (e.g. '#products' or '/app/')", max_length=300)),
                ('column', models.CharField(choices=[('products', 'Products'), ('company', 'Company'), ('access', 'Access')], max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['column', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='HeroShowcaseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Kids T-Shirts'", max_length=100)),
                ('description', models.TextField(help_text='Short description shown on the card')),
                ('price_label', models.CharField(blank=True, help_text="Price tag text (e.g. 'From ₹149'). Leave blank to hide.", max_length=50)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG markup for the card icon')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Showcase Card',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge_text', models.CharField(default='New Collection 2024', help_text="Small badge above the hero title (e.g. 'New Collection 2024')", max_length=100)),
                ('hero_title_line1', models.CharField(default='Premium Kids', help_text='First line of the hero heading', max_length=200)),
                ('hero_title_line2', models.CharField(default='Garments', help_text='Second line (shown in copper/italic)', max_length=200)),
                ('hero_description', models.TextField(default='Crafted with care for little ones. Explore our range of premium hosiery, comfortable pants, and vibrant t-shirts — designed for comfort, built to last.', help_text='Paragraph below the hero title')),
                ('hero_cta_primary_text', models.CharField(default='Explore Collection', max_length=100)),
                ('hero_cta_primary_link', models.CharField(default='#products', max_length=200)),
                ('hero_cta_secondary_text', models.CharField(default='Manage Inventory', max_length=100)),
                ('hero_cta_secondary_link', models.CharField(default='/app/', help_text='URL for the secondary button (e.g. login page)', max_length=200)),
                ('stat1_value', models.CharField(default='500+', max_length=20)),
                ('stat1_label', models.CharField(default='Products', max_length=50)),
                ('stat2_value', models.CharField(default='50+', max_length=20)),
                ('stat2_label', models.CharField(default='Designs', max_length=50)),
                ('stat3_value', models.CharField(default='1000+', max_length=20)),
                ('stat3_label', models.CharField(default='Happy Customers', max_length=50)),
                ('cta_title_line1', models.CharField(default='Ready to', max_length=200)),
                ('cta_title_line2', models.CharField(default='partner with us?', help_text='Shown in copper/italic', max_length=200)),
                ('cta_description', models.TextField(default='Log in to our inventory management system to track orders, manage batches, and keep your production running smoothly.')),
                ('cta_primary_text', models.CharField(default='Get Started', max_length=100)),
                ('cta_primary_link', models.CharField(default='/app/', max_length=200)),
                ('cta_secondary_text', models.CharField(default='View Products', max_length=100)),
                ('cta_secondary_link', models.CharField(default='#products', max_length=200)),
                ('categories_tag', models.CharField(default='Our Collection', max_length=100)),
                ('categories_title', models.CharField(default='Shop by Category', max_length=200)),
                ('categories_description', models.TextField(blank=True, default='From everyday essentials to special occasions — we have the perfect garment for every little one.')),
                ('products_tag', models.CharField(default='Bestsellers', max_length=100)),
                ('products_title', models.CharField(default='Featured Products', max_length=200)),
                ('products_description', models.TextField(blank=True, default='Our most popular garments, loved by parents and kids alike.')),
                ('whyus_tag', models.CharField(default='Why Kapil Enterprises', max_length=100)),
                ('whyus_title', models.CharField(default='Trusted by Businesses', max_length=200)),
                ('whyus_description', models.TextField(blank=True, default='We combine quality craftsmanship with modern manufacturing to deliver garments that exceed expectations.')),
                ('footer_description', models.TextField(default='Premium kids garment manufacturer. Hosiery, pants, t-shirts and more. Quality craftsmanship trusted by businesses across India.')),
                ('footer_copyright', models.CharField(default='2024 Kapil Enterprises. All rights reserved.', max_length=200)),
                ('footer_tagline', models.CharField(default='Crafted with care in India', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Configuration',
                'verbose_name_plural': 'Homepage Configuration',
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Link text shown in navbar', max_length=100)),
                ('url', models.CharField(help_text="URL or anchor (e.g. '#categories')", max_length=300)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='WhyUsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Quality Assured'", max_length=100)),
                ('description', models.TextField(help_text='Explanation of this benefit')),
                ('icon_svg', models.TextField(blank=True, help_text='SVG markup for the card icon')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Us Card',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Cotton Round Neck Tee — Multicolor Pack'", max_length=255)),
                ('category_label', models.CharField(blank=True, help_text="Override label shown above the name (e.g. 'Kids T-Shirt'). Falls back to category name.", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short product description (1-2 lines)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Current selling price (INR)', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original/MRP price for strikethrough display. Leave blank to hide.', max_digits=10, null=True)),
                ('sizes', models.CharField(blank=True, help_text="Comma-separated sizes to display (e.g. '2Y,4Y,6Y' or 'S,M,L,XL')", max_length=200)),
                ('badge', models.CharField(blank=True, choices=[('', 'No Badge'), ('new', 'New'), ('hot', 'Hot'), ('bestseller', 'Bestseller')], default='', help_text='Promotional badge shown on the product card', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Product image. If blank, a placeholder icon is shown.', null=True, upload_to='storefront/products/')),
                ('icon_svg', models.TextField(blank=True, help_text='SVG icon shown when no image is uploaded. Leave blank for default.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category this product belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='storefront.category')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
