# Generated by Django 5.0.1 on 2026-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image. If uploaded, replaces the SVG icon.', null=True, upload_to='storefront/categories/'),
        ),
        migrations.AddField(
            model_name='heroshowcasecard',
            name='image',
            field=models.ImageField(blank=True, help_text='Card image. If uploaded, replaces the SVG icon.', null=True, upload_to='storefront/showcase/'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='brand_logo',
            field=models.ImageField(blank=True, help_text="Brand logo shown in navbar and footer. Falls back to 'KE' monogram.", null=True, upload_to='storefront/brand/'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Optional hero background image. Overlays the gradient.', null=True, upload_to='storefront/hero/'),
        ),
        migrations.AddField(
            model_name='whyuscard',
            name='image',
            field=models.ImageField(blank=True, help_text='Card image/icon. If uploaded, replaces the SVG icon.', null=True, upload_to='storefront/whyus/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG markup for the category icon. Used when no image is uploaded.'),
        ),
        migrations.AlterField(
            model_name='heroshowcasecard',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG markup for the card icon. Used when no image is uploaded.'),
        ),
        migrations.AlterField(
            model_name='whyuscard',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG markup for the card icon. Used when no image is uploaded.'),
        ),
    ]
