from .dashboard import AddaDashboardView
from .product_views import (
    ProductArchiveView, ProductCreateView, ProductListView,
    ProductSizesEditView, ProductUpdateView,
)
from .adda_views import AddaListView, AddaCreateView, AddaDetailView
from .access_views import (
    StageListView, StageCreateView, StageUpdateView, StageDeleteView,
)
from .flow_views import ProductFlowEditView
from .pattern_views import (
    ProductPatternListView, ProductPatternCreateView,
    ProductPatternUpdateView, ProductPatternDeleteView,
    ProductPatternsEditView,
)
from .pattern_stage_views import (
    PatternWorkspaceView, PatternStartView, PatternSaveVideoView,
    PatternAddPhotoView, PatternRemovePhotoView, PatternCompleteView,
    PatternReopenView, PatternVerifyView, PatternUnverifyView,
    PatternSetSizesView,
    _build_pattern_context as _build_pattern_context,
)
from .barcode_gen_views import (
    BarcodeGenWorkspaceView, BarcodeGenStartView, BarcodeGenGenerateView,
    BarcodeGenCompleteView, BarcodeGenReopenView,
    _build_barcode_gen_context as _build_barcode_gen_context,
)
from .stage_views import (
    CuttingBreakupDeleteView,
    CuttingBreakupSaveView,
    CuttingBundleAddItemView,
    CuttingBundleAddPiecesView,
    CuttingBundleCreateView,
    CuttingBundleDeleteView,
    CuttingBundleItemDeleteView,
    CuttingBundleItemSaveView,
    CuttingCompleteView,
    CuttingDraftView,
    CuttingReopenView,
    CuttingStartView,
    CuttingWorkspaceCompleteView,
    CuttingWorkspaceView,
    LayeringAttachRollView,
    LayeringCompleteView,
    LayeringEntryRemoveView,
    LayeringEntryUpdateView,
    LayeringFullCreateAndAttachView,
    LayeringQuickCreateAndAttachView,
    LayeringRemoveRemainingClothView,
    LayeringReopenView,
    LayeringStartView,
    LayeringWorkspaceView,
    StagePanelView,
)

__all__ = [
    'AddaDashboardView',
    'ProductListView', 'ProductCreateView', 'ProductUpdateView', 'ProductArchiveView',
    'ProductSizesEditView',
    'AddaListView', 'AddaCreateView', 'AddaDetailView',
    'LayeringWorkspaceView',
    'StagePanelView',
    'LayeringStartView',
    'LayeringQuickCreateAndAttachView',
    'LayeringFullCreateAndAttachView',
    'LayeringRemoveRemainingClothView',
    'LayeringAttachRollView',
    'LayeringEntryUpdateView',
    'LayeringEntryRemoveView',
    'LayeringCompleteView',
    'LayeringReopenView',
    'CuttingCompleteView',
    'CuttingWorkspaceView',
    'CuttingStartView',
    'CuttingBreakupSaveView',
    'CuttingBreakupDeleteView',
    'CuttingBundleCreateView',
    'CuttingBundleAddItemView',
    'CuttingBundleAddPiecesView',
    'CuttingBundleItemSaveView',
    'CuttingBundleItemDeleteView',
    'CuttingBundleDeleteView',
    'CuttingDraftView',
    'CuttingWorkspaceCompleteView',
    'CuttingReopenView',
    'StageListView', 'StageCreateView', 'StageUpdateView', 'StageDeleteView',
    'ProductFlowEditView',
    'ProductPatternListView', 'ProductPatternCreateView',
    'ProductPatternUpdateView', 'ProductPatternDeleteView',
    'ProductPatternsEditView',
    'PatternWorkspaceView', 'PatternStartView', 'PatternSaveVideoView',
    'PatternAddPhotoView', 'PatternRemovePhotoView', 'PatternCompleteView',
    'PatternReopenView', 'PatternVerifyView', 'PatternUnverifyView',
    'PatternSetSizesView',
    'BarcodeGenWorkspaceView', 'BarcodeGenStartView', 'BarcodeGenGenerateView',
    'BarcodeGenCompleteView', 'BarcodeGenReopenView',
]
