# Generated by Django 5.0.1 on 2026-07-06 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0049_addastagerecord_production__complet_f3b3db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mat_code', models.SlugField(help_text="Physical label on the mat, e.g. 'MAT-01'.", max_length=32, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional display name.', max_length=100)),
                ('status', models.CharField(choices=[('uncommissioned', 'Uncommissioned'), ('active', 'Active'), ('retired', 'Retired')], default='uncommissioned', help_text='Uncommissioned mats cannot back a capture (gate at ADR-E).', max_length=16)),
                ('status_reason', models.CharField(blank=True, help_text='Mandatory when retired (F2: negative transitions carry reasons).', max_length=200)),
                ('commissioned_at', models.DateTimeField(blank=True, help_text='Set when tape-measured control distances were recorded.', null=True)),
                ('control_distances', models.JSONField(blank=True, default=dict, help_text='Commissioning tape measurements; payload carries schema_version.')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'calibration mat',
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, help_text="Globally-unique 'MRK-000001' (C14); assigned by marker_service via the shared next_reference discipline (Block 2B).", max_length=16, unique=True)),
                ('fabric_group', models.CharField(choices=[('body', 'Body'), ('rib', 'Rib'), ('collar', 'Collar'), ('trim', 'Trim'), ('other', 'Other')], default='body', help_text='A marker never mixes fabric groups.', max_length=16)),
                ('origin', models.CharField(choices=[('manual_photo', 'Manual (photo of chalk layout)'), ('generated', 'Generated'), ('imported', 'Imported'), ('adda_temporary', 'Adda temporary')], max_length=16)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('validated', 'Validated'), ('promoted', 'Promoted'), ('superseded', 'Superseded'), ('retired', 'Retired'), ('rejected', 'Rejected')], default='candidate', max_length=16)),
                ('status_reason', models.CharField(blank=True, help_text='Mandatory when retired/rejected (F2).', max_length=200)),
                ('label', models.CharField(blank=True, help_text='Floor name, e.g. "Master\'s 37in tube layout".', max_length=100)),
                ('usable_width_mm', models.PositiveIntegerField(help_text='Human-confirmed usable lay width in mm — never trusted from ClothRoll nominal inches.')),
                ('usable_width_band', models.PositiveIntegerField(editable=False, help_text='floor(usable_width_mm/10), stamped at creation (C10) — the hot resolution-query key.')),
                ('construction', models.CharField(choices=[('open', 'Open width'), ('tubular', 'Tubular (tube-flat)'), ('unknown', 'Unknown')], default='unknown', help_text='Tube-flat vs open width changes every utilization number.', max_length=8)),
                ('ratio', models.JSONField(blank=True, default=dict, help_text='INTEGER garments per repeat by size code; payload carries schema_version. CPSA percentages are prefill hints only.')),
                ('strategy', models.CharField(blank=True, help_text='Generated markers only (mixed/sectioned/fold-aware); blank for manual/imported.', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('adda', models.ForeignKey(blank=True, help_text='ONLY for origin=adda_temporary (D11): the run this marker was generated for; promotion clears nothing — history stays.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_markers', to='production.adda')),
                ('benchmarked_against', models.ForeignKey(blank=True, help_text='The baseline (usually manual) this marker competes with (C4).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='benchmark_children', to='patterns_ai.marker')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Permanent home — the Adda only CONSUMES (owner vision).', on_delete=django.db.models.deletion.PROTECT, related_name='markers', to='production.product')),
                ('supersedes', models.ForeignKey(blank=True, help_text='Lineage: the marker this one replaces (C20 biography).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_markers', to='patterns_ai.marker')),
            ],
            options={
                'verbose_name': 'marker',
            },
        ),
        migrations.CreateModel(
            name='MarkerUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plies', models.PositiveIntegerField(help_text='Lay plies this marker was cut over.')),
                ('repeats', models.PositiveIntegerField(default=1, help_text='Marker repeats along the lay (C7 — outcome math is wrong without it).')),
                ('measured_usable_width_mm', models.PositiveIntegerField(blank=True, help_text='Taped at the table for THIS lay; honest-NULL when unmeasured.', null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('adda', models.ForeignKey(help_text='FK INTO production — the allowed direction.', on_delete=django.db.models.deletion.PROTECT, related_name='marker_usages', to='production.adda')),
                ('confirmed_by', models.ForeignKey(help_text='The human act that writes this row.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='patterns_ai.marker')),
                ('stage_record', models.ForeignKey(blank=True, help_text='Optional: the cutting/layering stage record once known.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.addastagerecord')),
            ],
            options={
                'verbose_name': 'marker usage',
            },
        ),
        migrations.CreateModel(
            name='MarkerOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabric_in_mm', models.PositiveBigIntegerField(blank=True, help_text='Linear fabric laid, in mm (plies × lay length). Honest-NULL.', null=True)),
                ('garments_cut', models.PositiveIntegerField(blank=True, help_text='From APSCPB at recording time. Honest-NULL.', null=True)),
                ('garments_packed', models.PositiveIntegerField(blank=True, null=True)),
                ('leftover_mm', models.PositiveBigIntegerField(blank=True, help_text='End-of-lay leftover length in mm, if measured.', null=True)),
                ('quality_flags', models.JSONField(blank=True, default=dict, help_text='Data-quality flags (confounders, dev-fixture, unmeasured…).')),
                ('facts_schema_version', models.PositiveSmallIntegerField(default=1, help_text='Version of THIS row shape (F3).')),
                ('recorded_by', models.ForeignKey(help_text="Outcome facts are written by an explicit human 'record outcome' action (readiness N-6).", on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usage', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outcome', to='patterns_ai.markerusage')),
            ],
            options={
                'verbose_name': 'marker outcome',
            },
        ),
        migrations.CreateModel(
            name='PatternPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabric_group', models.CharField(choices=[('body', 'Body'), ('rib', 'Rib'), ('collar', 'Collar'), ('trim', 'Trim'), ('other', 'Other')], default='body', help_text='Markers never mix fabric groups (V3 concept model).', max_length=16)),
                ('is_pair', models.BooleanField(default=False, help_text='Cut as mirrored pair (e.g. sleeves).')),
                ('on_fold', models.BooleanField(default=False, help_text='Cut on fold — fold-edge semantics land with geometry.')),
                ('notes', models.TextField(blank=True)),
                ('assignment', models.OneToOneField(blank=True, help_text='Optional link to the product↔pattern assignment row.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patterns_ai_piece', to='production.productpatternassignment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pattern', models.ForeignKey(help_text='Name/identity link ONLY into the shared pattern library; pieces_count stays on ProductPatternAssignment (never duplicated).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productpattern')),
                ('product', models.ForeignKey(help_text='Owning product — the permanent home (owner vision).', on_delete=django.db.models.deletion.PROTECT, related_name='pattern_pieces', to='production.product')),
            ],
            options={
                'verbose_name': 'pattern piece',
            },
        ),
        migrations.CreateModel(
            name='PatternPieceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField(help_text='1,2,3… per piece; assigned by the single-writer service.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('status_reason', models.CharField(blank=True, help_text='Mandatory on rejection (F2).', max_length=200)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Human confirmation = the source of truth (owner lock).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='patterns_ai.patternpiece')),
                ('superseded_by', models.ForeignKey(blank=True, help_text='Forward lineage; set when a newer version confirms.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes_versions', to='patterns_ai.patternpieceversion')),
            ],
            options={
                'verbose_name': 'pattern piece version',
                'ordering': ['piece_id', 'version_no'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(help_text="Deterministic mechanism id, e.g. 'garment_template:tshirt@r1' or 'copy_from:PRODUCT-CODE'. FK to GarmentTemplate revision lands with that model (later block).", max_length=100)),
                ('payload', models.JSONField(default=dict, help_text='What was suggested; payload carries schema_version.')),
                ('outcome', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('modified', 'Accepted with modifications'), ('rejected', 'Rejected')], default='offered', max_length=16)),
                ('outcome_reason', models.CharField(blank=True, help_text='Mandatory on rejection (F2).', max_length=200)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product-homed (owner vision: suggestions live with the product).', on_delete=django.db.models.deletion.PROTECT, related_name='pattern_suggestions', to='production.product')),
            ],
            options={
                'verbose_name': 'suggestion event',
            },
        ),
        migrations.AddConstraint(
            model_name='calibrationmat',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'retired'), _negated=True), models.Q(('status_reason', ''), _negated=True), _connector='OR'), name='pai_mat_retired_requires_reason'),
        ),
        migrations.AddIndex(
            model_name='marker',
            index=models.Index(fields=['product', 'fabric_group', 'usable_width_band'], name='patterns_ai_product_70c3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='marker',
            index=models.Index(fields=['status'], name='patterns_ai_status_b86ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='marker',
            index=models.Index(fields=['origin'], name='patterns_ai_origin_dfe6a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='marker',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('adda__isnull', False), ('origin', 'adda_temporary')), models.Q(models.Q(('origin', 'adda_temporary'), _negated=True), ('adda__isnull', True)), _connector='OR'), name='pai_marker_adda_iff_temporary'),
        ),
        migrations.AddConstraint(
            model_name='marker',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status__in', ('retired', 'rejected')), _negated=True), models.Q(('status_reason', ''), _negated=True), _connector='OR'), name='pai_marker_negative_status_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='marker',
            constraint=models.CheckConstraint(check=models.Q(('usable_width_mm__gt', 0)), name='pai_marker_width_positive'),
        ),
        migrations.AddIndex(
            model_name='markerusage',
            index=models.Index(fields=['marker', 'adda'], name='patterns_ai_marker__11c954_idx'),
        ),
        migrations.AddIndex(
            model_name='markerusage',
            index=models.Index(fields=['adda'], name='patterns_ai_adda_id_61688b_idx'),
        ),
        migrations.AddConstraint(
            model_name='markerusage',
            constraint=models.CheckConstraint(check=models.Q(('plies__gte', 1)), name='pai_usage_plies_positive'),
        ),
        migrations.AddConstraint(
            model_name='markerusage',
            constraint=models.CheckConstraint(check=models.Q(('repeats__gte', 1)), name='pai_usage_repeats_positive'),
        ),
        migrations.AddConstraint(
            model_name='markerusage',
            constraint=models.CheckConstraint(check=models.Q(('voided_at__isnull', True), models.Q(('void_reason', ''), _negated=True), _connector='OR'), name='pai_usage_void_requires_reason'),
        ),
        migrations.AddIndex(
            model_name='patternpiece',
            index=models.Index(fields=['product', 'fabric_group'], name='patterns_ai_product_4880c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='patternpiece',
            constraint=models.UniqueConstraint(fields=('product', 'pattern'), name='pai_piece_unique_per_product'),
        ),
        migrations.AddConstraint(
            model_name='patternpieceversion',
            constraint=models.UniqueConstraint(fields=('piece', 'version_no'), name='pai_version_unique_per_piece'),
        ),
        migrations.AddConstraint(
            model_name='patternpieceversion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('status_reason', ''), _negated=True), _connector='OR'), name='pai_version_rejected_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='patternpieceversion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'confirmed'), _negated=True), models.Q(('confirmed_by__isnull', False), ('confirmed_at__isnull', False)), _connector='OR'), name='pai_version_confirmed_requires_audit'),
        ),
        migrations.AddIndex(
            model_name='suggestionevent',
            index=models.Index(fields=['product', 'outcome'], name='patterns_ai_product_c13203_idx'),
        ),
        migrations.AddConstraint(
            model_name='suggestionevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('outcome', 'rejected'), _negated=True), models.Q(('outcome_reason', ''), _negated=True), _connector='OR'), name='pai_suggestion_rejected_requires_reason'),
        ),
    ]
