# Generated by Django 5.0.1 on 2026-07-06 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerTransitionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, help_text='Previous status; empty string for the CREATION event.', max_length=16)),
                ('to_status', models.CharField(help_text='New status after the transition.', max_length=16)),
                ('reason', models.CharField(blank=True, help_text='Mandatory upstream for negative transitions; recorded verbatim.', max_length=200)),
                ('transition_version', models.PositiveSmallIntegerField(help_text='Version of the transition rule-set that produced this event (marker_service.TRANSITIONS_VERSION at write time).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Event context (e.g. origin at creation, superseded_by ref).')),
                ('actor', models.ForeignKey(help_text='Who performed the transition (F2: attributed decisions).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marker', models.ForeignKey(help_text='The marker this event belongs to (PROTECT: history outlives intent).', on_delete=django.db.models.deletion.PROTECT, related_name='transition_events', to='patterns_ai.marker')),
            ],
            options={
                'verbose_name': 'marker transition event',
                'ordering': ['marker_id', 'id'],
                'indexes': [models.Index(fields=['marker', 'id'], name='patterns_ai_marker__5d44d5_idx')],
            },
        ),
    ]
