# Generated by Django 5.0.1 on 2026-07-06 17:58

import django.db.models.deletion
import patterns_ai.models.capture
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0002_markertransitionevent'),
        ('production', '0049_addastagerecord_production__complet_f3b3db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('marker_photo', 'Manual marker photo'), ('pattern_capture', 'Pattern capture (geometry era)')], default='marker_photo', max_length=20)),
                ('source', models.CharField(choices=[('camera', 'Camera'), ('gallery', 'Gallery upload')], max_length=10)),
                ('file', models.FileField(help_text='The immutable original. Never replaced; never served raw at scale (ADR-G).', max_length=255, upload_to=patterns_ai.models.capture.capture_upload_to)),
                ('original_filename', models.CharField(blank=True, help_text='Sanitized client filename, display only (never used for storage).', max_length=200)),
                ('content_type', models.CharField(max_length=40)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(help_text='Streaming SHA-256 of the stored bytes — the integrity anchor.', max_length=64)),
                ('status', models.CharField(choices=[('stored', 'Stored'), ('corrupt', 'Integrity check failed'), ('retired', 'Retired')], default='stored', max_length=10)),
                ('status_reason', models.CharField(blank=True, help_text='Mandatory when retired/corrupt (F2).', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Client-declared context only in Block 3A (no EXIF processing yet).')),
                ('mat', models.ForeignKey(blank=True, help_text='Custody chain for pattern captures (geometry era); NULL for marker photos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captures', to='patterns_ai.calibrationmat')),
                ('product', models.ForeignKey(help_text='Product-homed (owner vision: capture assets live with the product).', on_delete=django.db.models.deletion.PROTECT, related_name='capture_assets', to='production.product')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'capture asset',
                'indexes': [models.Index(fields=['product', 'kind', 'status'], name='patterns_ai_product_139038_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='captureasset',
            constraint=models.UniqueConstraint(fields=('product', 'sha256'), name='pai_capture_unique_content_per_product'),
        ),
        migrations.AddConstraint(
            model_name='captureasset',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status__in', ('retired', 'corrupt')), _negated=True), models.Q(('status_reason', ''), _negated=True), _connector='OR'), name='pai_capture_negative_status_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='captureasset',
            constraint=models.CheckConstraint(check=models.Q(('size_bytes__gt', 0)), name='pai_capture_size_positive'),
        ),
    ]
