# Generated by Django 5.0.1 on 2026-07-06 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0003_captureasset_and_more'),
        ('production', '0049_addastagerecord_production__complet_f3b3db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='The chalk-layout photo (REQUIRED for manual_photo origin — service-enforced); one photo backs at most one marker.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_marker_photo', to='patterns_ai.captureasset'),
        ),
        migrations.AddConstraint(
            model_name='marker',
            constraint=models.UniqueConstraint(condition=models.Q(('photo__isnull', False)), fields=('photo',), name='pai_marker_photo_used_once'),
        ),
    ]
