# Generated by Django 5.0.1 on 2026-07-06 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0004_marker_photo_marker_pai_marker_photo_used_once'),
        ('production', '0049_addastagerecord_production__complet_f3b3db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationmat',
            name='board_spec',
            field=models.JSONField(blank=True, default=dict, help_text='ChArUco spec: {"schema_version":1,"squares_x":14,"squares_y":10,"square_mm":100,"marker_mm":75,"aruco_dict":"DICT_5X5_1000"}.'),
        ),
        migrations.CreateModel(
            name='CalibrationMatCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('commissioning', 'Commissioning'), ('recheck', 'Recheck')], max_length=16)),
                ('evidence', models.JSONField(default=dict, help_text='calibrate.py output: metrics + self-check + gate; payload carries pipeline_version.')),
                ('passed', models.BooleanField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('capture', models.ForeignKey(blank=True, help_text='The photo this check ran on (optional for tape-only rows).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patterns_ai.captureasset')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='patterns_ai.calibrationmat')),
            ],
            options={
                'verbose_name': 'calibration mat check',
                'ordering': ['mat_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GeometryExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backend', models.CharField(default='classical', max_length=16)),
                ('pipeline_version', models.CharField(max_length=16)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('gate', models.JSONField(blank=True, default=dict, help_text='ADR-E §3 hard-gate verdict incl. recorded refusal reasons.')),
                ('geometry', models.JSONField(blank=True, help_text='Canonical ADR-C proposal payload; NULL when the gate refused.', null=True)),
                ('confidence', models.JSONField(blank=True, default=dict, help_text='Component-visible score; display only, never auto-accept.')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='proposed', max_length=16)),
                ('status_reason', models.CharField(blank=True, help_text='Mandatory on rejection (F2).', max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extractions', to='patterns_ai.captureasset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extractions', to='patterns_ai.patternpiece')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('size', models.ForeignKey(help_text='ADR-D2: geometry is per-size; the size this photo captures.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productsize')),
            ],
            options={
                'verbose_name': 'geometry extraction',
            },
        ),
        migrations.CreateModel(
            name='PatternSetLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32)),
                ('label', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pattern_set_labels', to='production.product')),
            ],
            options={
                'verbose_name': 'pattern set label',
            },
        ),
        migrations.AddField(
            model_name='patternpieceversion',
            name='set_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='patterns_ai.patternsetlabel'),
        ),
        migrations.CreateModel(
            name='PieceSizeGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geometry', models.JSONField(help_text='Canonical payload (integer um, y-up, CCW outer; ADR-C).')),
                ('chord_tolerance_um', models.PositiveIntegerField(default=500)),
                ('trust_grade', models.CharField(choices=[('measured', 'Measured (tape-accepted)'), ('photo_calibrated', 'Photo-calibrated'), ('uncalibrated', 'Uncalibrated')], default='uncalibrated', help_text='ADR-E §7; stamped at confirm (tape acceptance => measured).', max_length=20)),
                ('tape_acceptance', models.JSONField(blank=True, default=dict, help_text='Numeric tape acceptance recorded at confirm (ADR-E §5).')),
                ('copied_from', models.ForeignKey(blank=True, help_text='ADR-D2 copy-forward provenance (new version carries rows).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='patterns_ai.piecesizegeometry')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productsize')),
                ('source_extraction', models.ForeignKey(blank=True, help_text='NULL for DXF imports and manual entry; custody chain otherwise.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='geometry_rows', to='patterns_ai.geometryextraction')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_geometries', to='patterns_ai.patternpieceversion')),
            ],
            options={
                'verbose_name': 'piece size geometry',
            },
        ),
        migrations.AddIndex(
            model_name='geometryextraction',
            index=models.Index(fields=['piece', 'size', 'status'], name='patterns_ai_piece_i_dd3cbd_idx'),
        ),
        migrations.AddConstraint(
            model_name='geometryextraction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('status_reason', ''), _negated=True), _connector='OR'), name='pai_extraction_rejected_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='geometryextraction',
            constraint=models.CheckConstraint(check=models.Q(('status', 'proposed'), models.Q(('reviewed_by__isnull', False), ('reviewed_at__isnull', False)), _connector='OR'), name='pai_extraction_review_requires_audit'),
        ),
        migrations.AddConstraint(
            model_name='patternsetlabel',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='pai_setlabel_unique_per_product'),
        ),
        migrations.AddConstraint(
            model_name='piecesizegeometry',
            constraint=models.UniqueConstraint(fields=('version', 'size'), name='pai_geometry_unique_version_size'),
        ),
    ]
