# Generated by Django 5.0.1 on 2026-07-07 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0005_calibrationmat_board_spec_calibrationmatcheck_and_more'),
        ('production', '0049_addastagerecord_production__complet_f3b3db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedMarkerCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine', models.CharField(max_length=16)),
                ('placements', models.JSONField()),
                ('marker_length_mm', models.DecimalField(decimal_places=2, help_text='Engine-run FACT, re-measured by the independent verifier.', max_digits=9)),
                ('verification', models.JSONField(help_text='shapely verdict: overlap / width containment / count — computed in the runtime, never trusted from the engine.')),
                ('seed', models.PositiveIntegerField(default=42)),
                ('trials', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'generated marker candidate',
            },
        ),
        migrations.AddField(
            model_name='marker',
            name='candidate',
            field=models.ForeignKey(blank=True, help_text='Evidence chain for generated markers (D11 promotion).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promoted_markers', to='patterns_ai.generatedmarkercandidate'),
        ),
        migrations.CreateModel(
            name='MarkerGenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usable_width_mm', models.PositiveIntegerField()),
                ('params', models.JSONField(help_text='Full request + the exact geometry rows consumed (reproducibility spine; payload carries schema_version).')),
                ('pipeline_version', models.CharField(max_length=16)),
                ('errors', models.JSONField(blank=True, default=dict, help_text='Per-engine refusals, recorded honestly.')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marker_generation_runs', to='production.product')),
            ],
            options={
                'verbose_name': 'marker generation run',
            },
        ),
        migrations.AddField(
            model_name='generatedmarkercandidate',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='patterns_ai.markergenerationrun'),
        ),
        migrations.AddIndex(
            model_name='markergenerationrun',
            index=models.Index(fields=['product', '-id'], name='patterns_ai_product_ff5f68_idx'),
        ),
        migrations.AddConstraint(
            model_name='generatedmarkercandidate',
            constraint=models.CheckConstraint(check=models.Q(('marker_length_mm__gt', 0)), name='pai_candidate_length_positive'),
        ),
    ]
