# Generated by Django 5.0.1 on 2026-07-07 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0006_generatedmarkercandidate_marker_candidate_and_more'),
        ('production', '0049_addastagerecord_production__complet_f3b3db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patternpiece',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='Optional pieces (e.g. Pocket) join a layout only when their designs exist for the requested sizes; missing optional designs never block generation. Default False = required (validation cannot silently weaken).'),
        ),
        migrations.AddField(
            model_name='patternpiece',
            name='reference_image',
            field=models.ForeignKey(blank=True, help_text='Display-only illustration (kind=reference_image) — NEVER a geometry source; extraction refuses non-pattern-capture kinds structurally.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference_for_pieces', to='patterns_ai.captureasset'),
        ),
        migrations.AlterField(
            model_name='captureasset',
            name='kind',
            field=models.CharField(choices=[('marker_photo', 'Manual marker photo'), ('pattern_capture', 'Pattern capture (geometry era)'), ('reference_image', 'Reference image (display only)')], default='marker_photo', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductFabricProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_width_mm', models.PositiveIntegerField(blank=True, help_text='Prefills Generate + the editor; never authoritative.', null=True)),
                ('default_length_mm', models.PositiveIntegerField(blank=True, help_text='Default layer length (fabric height) prefill.', null=True)),
                ('default_spacing_mm', models.DecimalField(blank=True, decimal_places=1, help_text='Default piece spacing prefill.', max_digits=4, null=True)),
                ('fabric_type', models.CharField(blank=True, help_text='Optional metadata (display + export summary only).', max_length=60)),
                ('gsm', models.PositiveSmallIntegerField(blank=True, help_text='Optional fabric weight metadata.', null=True)),
                ('lay_mode', models.CharField(blank=True, help_text='Optional lay metadata (e.g. face-up single-ply).', max_length=40)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fabric_profile', to='production.product')),
            ],
            options={
                'verbose_name': 'product fabric profile',
            },
        ),
        migrations.CreateModel(
            name='ProductionLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField()),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approved_layout', models.ForeignKey(help_text='Pointer to an existing immutable saved layout — approval never duplicates layout data.', on_delete=django.db.models.deletion.PROTECT, related_name='production_designations', to='patterns_ai.generatedmarkercandidate')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='production_layout', to='production.product')),
            ],
            options={
                'verbose_name': 'production layout designation',
            },
        ),
    ]
