# Generated by Django 5.0.1 on 2026-07-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0007_patternpiece_is_optional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecesizegeometry',
            name='geometry_contract_version',
            field=models.CharField(default='adr-c.1', help_text='Semantic contract of the payload (ADR-C rev); stamped by the single-writer service, never edited.', max_length=16),
        ),
    ]
