# Generated by Django 5.0.1 on 2026-07-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0008_piecesizegeometry_geometry_contract_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternpiece',
            name='grain_rule',
            field=models.CharField(choices=[('strict', 'On grain (0° only)'), ('two_way', 'Two-way (180° allowed)'), ('free', 'Free (any rotation)')], default='two_way', help_text='Blueprint rule: how this piece may rotate vs fabric grain.', max_length=16),
        ),
    ]
