# Generated by Django 5.0.1 on 2026-07-09 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0009_patternpiece_grain_rule'),
        ('production', '0049_addastagerecord_production__complet_f3b3db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layout_uid', models.CharField(editable=False, help_text='Immutable ID (LAY-<product>-NNNNNN) for ERP/Adda/barcode/audit references — never changes, never reused.', max_length=40, unique=True)),
                ('name', models.CharField(blank=True, help_text='Human label; the uid is the truth.', max_length=80)),
                ('version_no', models.PositiveIntegerField(help_text='Per-product human counter V1, V2, … (append-only).')),
                ('fabric_group', models.CharField(help_text='LAW 12: one layout = one fabric group; frozen at save.', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='active', max_length=16)),
                ('approved_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(help_text='Rule 8: only an explicit HUMAN act approves.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(help_text='The immutable payload — placements/length/verification live THERE; approval points, never copies.', on_delete=django.db.models.deletion.PROTECT, related_name='library_approvals', to='patterns_ai.generatedmarkercandidate')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_layouts', to='production.product')),
                ('supersedes', models.ForeignKey(blank=True, help_text='Lineage: the layout this one replaces (rule 5).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_layouts', to='patterns_ai.approvedlayout')),
            ],
            options={
                'verbose_name': 'approved layout',
                'ordering': ['product_id', '-version_no'],
                'indexes': [models.Index(fields=['product', 'status'], name='patterns_ai_product_f15f29_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='approvedlayout',
            constraint=models.UniqueConstraint(fields=('product', 'version_no'), name='pai_layout_version_per_product'),
        ),
    ]
