# Generated by Django 5.0.1 on 2026-07-09 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0010_approvedlayout_and_more'),
        ('production', '0049_addastagerecord_production__complet_f3b3db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedLayoutUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabric_group', models.CharField(editable=False, help_text='F2 denorm from the layout — constraint key only.', max_length=16)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, help_text='Mandatory when voiding — history explains itself.', max_length=200)),
                ('adda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layout_usages', to='production.adda')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='patterns_ai.approvedlayout')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stage_record', models.ForeignKey(blank=True, help_text="Stamped at pattern-stage completion (8D) — the audit join, mirroring MarkerUsage's designed shape.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.addastagerecord')),
            ],
            options={
                'verbose_name': 'approved layout usage',
                'indexes': [models.Index(fields=['adda', 'voided_at'], name='patterns_ai_adda_id_858888_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='approvedlayoutusage',
            constraint=models.UniqueConstraint(condition=models.Q(('voided_at__isnull', True)), fields=('adda', 'fabric_group'), name='pai_usage_one_active_per_adda_group'),
        ),
        migrations.AddConstraint(
            model_name='approvedlayoutusage',
            constraint=models.CheckConstraint(check=models.Q(('voided_at__isnull', True), models.Q(('void_reason', ''), _negated=True), _connector='OR'), name='pai_layout_usage_void_requires_reason'),
        ),
    ]
