# Generated by Django 5.0.1 on 2026-07-10 08:39

import django.db.models.deletion
import patterns_ai.models.geometry
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0011_approvedlayoutusage_and_more'),
        ('production', '0049_addastagerecord_production__complet_f3b3db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patternpiece',
            name='expected_notches',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Expected notch count per size (advisory — a mismatch shows honestly, never blocks).', null=True),
        ),
        migrations.AddField(
            model_name='patternpiece',
            name='seam_allowance_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Declared seam allowance (mm). Geometry stays the CUT line (ADR-C); this is declared metadata, not an offset.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='geometryextraction',
            name='capture',
            field=models.ForeignKey(blank=True, help_text='Photo custody chain; NULL for non-photo adapters (M2).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extractions', to='patterns_ai.captureasset'),
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('photo', 'Photo (calibration mat)'), ('dxf', 'DXF file'), ('svg', 'SVG file'), ('pdf', 'PDF file'), ('png', 'PNG image'), ('manual_dims', 'Manual dimensions'), ('ai_api', 'External AI service')], max_length=16)),
                ('file', models.FileField(blank=True, help_text='Original DXF/SVG bytes — evidence is a kept fact.', max_length=255, null=True, upload_to=patterns_ai.models.geometry.evidence_upload_to)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Adapter input (e.g. manual dims {width_mm, height_mm}).')),
                ('status', models.CharField(choices=[('received', 'Received'), ('proposed', 'Proposal created'), ('refused', 'Adapter refused')], default='received', max_length=10)),
                ('refusal_reason', models.CharField(blank=True, help_text='Honest recorded refusal (ladder rule) — mandatory when refused.', max_length=300)),
                ('capture', models.ForeignKey(blank=True, help_text='Photo evidence wraps the immutable CaptureAsset.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to='patterns_ai.captureasset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to='patterns_ai.patternpiece')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productsize')),
            ],
            options={
                'verbose_name': 'evidence item',
            },
        ),
        migrations.AddField(
            model_name='geometryextraction',
            name='evidence',
            field=models.ForeignKey(blank=True, help_text='M2 Evidence Stack link; NULL on pre-M2 photo rows.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='patterns_ai.evidenceitem'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['piece', 'size', 'status'], name='patterns_ai_piece_i_d345a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidenceitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'refused'), _negated=True), models.Q(('refusal_reason', ''), _negated=True), _connector='OR'), name='pai_evidence_refused_requires_reason'),
        ),
    ]
