# Generated by Django 5.0.1 on 2026-07-10 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0013_alter_piecesizegeometry_geometry_contract_version'),
        ('production', '0049_addastagerecord_production__complet_f3b3db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The factory name: "Body+Pocket · double · 42″". A LABEL — the planner never branches on it.', max_length=80)),
                ('fabric_group', models.CharField(max_length=16)),
                ('layering_type', models.CharField(choices=[('single', 'Single layer'), ('double', 'Double layer'), ('tubular', 'Tubular')], default='single', max_length=10)),
                ('piece_ids', models.JSONField(blank=True, default=list, help_text='Pieces this marker covers (ids) — the SEPARATE_PANEL/BODY_PLUS_POCKET decision as data.')),
                ('size_ratio', models.JSONField(blank=True, default=dict, help_text='{size_id: garments-per-lay} — the size mix.')),
                ('optimize_intent', models.CharField(choices=[('fast', 'Fast'), ('balanced', 'Balanced'), ('best', 'Best')], default='balanced', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft state — recipes are knowledge, never deleted.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marker_recipes', to='production.product')),
            ],
            options={
                'verbose_name': 'marker recipe',
                'indexes': [models.Index(fields=['product', 'is_active'], name='patterns_ai_product_c037eb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='manufacturingstrategy',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='pai_recipe_unique_per_product'),
        ),
    ]
