# Generated by Django 5.0.1 on 2026-07-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0014_manufacturingstrategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecesizegeometry',
            name='geometry_contract_version',
            field=models.CharField(default='adr-c.3', help_text='Semantic contract of the payload (ADR-C rev); stamped by the single-writer service, never edited.', max_length=16),
        ),
    ]
