# Generated by Django 5.0.1 on 2026-07-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0015_alter_piecesizegeometry_geometry_contract_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingstrategy',
            name='layering_type',
            field=models.CharField(choices=[('single', 'Single layer'), ('double', 'Double layer (legacy = open)'), ('double_open', 'Double — open (2 plies)'), ('double_folded', 'Double — folded (crease)'), ('tubular', 'Tubular')], default='single', max_length=16),
        ),
    ]
