# Generated by Django 5.0.1 on 2026-07-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_ai', '0016_alter_manufacturingstrategy_layering_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceitem',
            name='kind',
            field=models.CharField(choices=[('photo', 'Photo (calibration mat)'), ('photo_plain', 'Photo (plain background)'), ('dxf', 'DXF file'), ('svg', 'SVG file'), ('pdf', 'PDF file'), ('png', 'PNG image'), ('manual_dims', 'Manual dimensions'), ('ai_api', 'External AI service')], max_length=16),
        ),
    ]
